### ISSUE TITLE
Permanent day is forced

### ISSUE THREAD

**Issue by zhuowei** [GlowstoneMC/Glowstone-Legacy#12]
In GlowWorld's pulse function, the time is always modded by 12000 to force permenent day. Why is that?

**Comment by SpaceManiac** [comment]
Mainly so I don't yet have to deal with the lighting issues that come about as a result of the day/night cycle. It'll be changed back to normal (modded by 24000) once the lighting engine is in and semi-stable.

**Comment by zhuowei** [comment]
Minecraft 1.8, according to Notch (https://mobile.twitter.com/notch/status/79526884454567936), will be able to render day/night cycles without updating the lighting, so perhaps the limit could be removed after the release of 1.8.
