### ISSUE TITLE
Branch review: iterable

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#122]
It'd be great if someone who knows more about these things than me could review the [`iterable` branch](https://github.com/SpaceManiac/Glowstone/compare/iterable) and assure me that what I'm doing makes sense and is worth the trouble. The goal is to avoid having to create new `GlowPlayer` arrays all the time. I got changes in usage patterns looking like this:

![iterable-graph](https://cloud.githubusercontent.com/assets/222630/3310813/692689fe-f6bb-11e3-8098-a91a0d2d4b9e.png)

but I'm not entirely certain what's coincidence or other things happening on my system and what's an actual improvement.

**Comment by SpaceManiac** [comment]
Needs to be updated to provide a view: Bukkit/Bukkit@0d9771acf6e59ca77fea3f55a33508661bcf7a5d (CB impl: Bukkit/CraftBukkit@e6cd8c017fe6991600c6af1955ace9d517a7080f).

**Comment by turt2live** [comment]
I can't find this branch or any record of it being pulled/merged anywhere. What happened to it?

**Comment by SpaceManiac** [comment]
A partial solution to the same problem was included in daaae748c4 and the branch was removed shortly after.
