### ISSUE TITLE
Update bans for UUIDs

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#123]
The ban/whitelist/op system still uses the pre-1.7.9 format. It needs to be updated to match what Vanilla/CraftBukkit use, or at least some format which functions equivalently. The old files would ideally be automatically updated to the new format (and then renamed to something different, such as `<filename>.txt.old`). The old files do not need to be kept up to date after the conversion has happened, only the new files.
- [x] Update whitelist and ops list to json.
- [x] Update name and IP ban lists to json.
- [ ] Use UUIDs instead of names for bans (pending Bukkit API changes?).
- [ ] Migrate old files (is this even needed?).

The format of the new files are as follows:

``` javascript
// banned-ips.json
[
  {
    // matches items present in old banned-ips.txt
    "ip": "127.0.0.1",
    "created": "2014-02-12 02:47:55 -0600",
    "source": "CONSOLE",
    "expires": "forever",
    "reason": "Test ban."
  }
]
// banned-players.json
[
  {
    // UUID is used for the check; name is for readability
    "uuid": "e40616ab-0727-4bbc-a187-6a428241a9b6",
    "name": "SpaceManiac",
    // the rest of the fields match the old banned-names.txt
    "created": "2014-05-05 18:02:39 -0500",
    "source": "SpaceManiac",
    "expires": "forever",
    "reason": "Banned by an operator."
  }
]
// ops.json
[
  {
    // UUID is used for the check; name is for readability
    "uuid": "e40616ab-0727-4bbc-a187-6a428241a9b6",
    "name": "SpaceManiac",
    // level ignored on read and always set to 4 on write
    // used for vanilla's wacky permission system which we don't need
    "level": 4
  }
]
// whitelist.json
[
  {
    // UUID is used for the check; name is for readability
    "uuid": "e40616ab-0727-4bbc-a187-6a428241a9b6",
    "name": "SpaceManiac"
  }
]
```

**Comment by turt2live** [comment]
This issue was resolved a while ago. A ticket has been created as a side effect bug: https://github.com/GlowstoneMC/Glowstone/issues/227
