### ISSUE TITLE
tellraw command

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone-Legacy#124]
The `tellraw` command is unimplemented:

```
>tellraw
13:15:36 [INFO] Unknown command "tellraw", try "help"
```

would be nice to have this :) usage is `/tellraw player raw-json-message`, allows sending formatted JSON text (spec at http://minecraft.gamepedia.com/Commands#Raw_JSON_Text) in the http://wiki.vg/Protocol#Chat_Message packet, beyond what the Bukkit API sendMessage() (and even sendRawMessage()) allows (preformatted into `{"text": …}`), until the RichMessage API at github.com/Bukkit/Bukkit/pull/1065 is implemented

**Comment by Sleaker** [comment]
@deathcap - I don't know if that's a good idea, the reason why bukkit probably doesn't do it is because if you messup the json data you disconnect the client.  Just something to be aware of.

**Comment by navarr** [comment]
It's probably not implemented in Bukkit because they'd have to do a validation layer before then.  Which honestly probably shouldn't be too difficult (other than the annoyance of parsing JSON)

**Comment by SpaceManiac** [comment]
The command isn't in Bukkit proper because there's no Bukkit API to accomplish what it does. In CraftBukkit it's just a passthrough to the Mojang command.

This would be trivial to implement if error-checking was disregarded, but I'm not sure it's the best solution.

**Comment by deathcap** [comment]
Well, a proper Bukkit API is probably the better solution, they're working on it at https://github.com/Bukkit/Bukkit/pull/1065 and it should solve the client validation problem since the server will generate the JSON message from the `RichMessage` API calls, which abstract away the JSON implementation details so it could refuse to generate invalid messages. Looks like this API is a ways off, though (but once/if it is integrated I'd be happy to switch to it).

Meanwhile, I think implementing the `/tellraw` command is at least, most expedient, and will increase plugin compatibility. I'm developing a plugin, testing on Glowstone, and couldn't find any compatible mechanism to send formatted text. It seems that plugin developers for other implementations either resort to calling into Minecraft to send the raw 0x02 http://wiki.vg/Protocol#Chat_Message packet, or using `dispatchCommand()` on the server to send `/tellraw`. I could chose the former but would have to implement it differently for each Bukkit server implementation; if Glowstone supports /tellraw then the same command would work on both Spigot and Glowstone.

Also, some validation can be performed without much difficulty. Glowstone's `ChatMessage` class has a constructor accepting a `JSONObject`, which /tellraw could pass parsed JSON (= syntactically valid), preventing invalid JSON from reaching the client. This wouldn't block semantically invalid messages, however (arrays where objects are expected, etc.), which still could crash the client. But a permission node could prevent arbitrary users sending these raw messages.

Anyways, here's my PR, feedback welcome: https://github.com/SpaceManiac/Glowstone/pull/125
