### ISSUE TITLE
crash during shutdown

### ISSUE THREAD

**Issue by alexandrage** [GlowstoneMC/Glowstone-Legacy#129]
02:34:53 [WARNING] Rogue thread: Thread[pool-2-thread-1,5,main]
02:34:53 [WARNING] at sun.misc.Unsafe.park(Native Method)
02:34:53 [WARNING] at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
02:34:53 [WARNING] at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)

02:34:53 [WARNING] at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)

02:34:53 [WARNING] at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
02:34:53 [WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
02:34:53 [WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
02:34:53 [WARNING] at java.lang.Thread.run(Thread.java:745)

**Comment by SpaceManiac** [comment]
Odd. Any plugins? Environment information?

**Comment by turt2live** [comment]
@alexandrage Any further information on this?

**Comment by SpaceManiac** [comment]
Closed in favor of #179.
