### ISSUE TITLE
Configurable server messages

### ISSUE THREAD

**Issue by Xesau** [GlowstoneMC/Glowstone-Legacy#134]
It would be cool to be able to customize the server shutdown message etc.
Maybe add this to the config & GlowServer.java?

**Comment by ewized** [comment]
If they did do it the best way would be to have locale files, in the server jar ex `en_US.properties`

**Comment by Xesau** [comment]
No.
It's way easier to set a custom message like:
'§cThe server is shutting down. We will be back online soon!'

**Comment by ewized** [comment]
That may be easier but the best why is to support locales...

**Comment by SpaceManiac** [comment]
For the record, the `/stop` command supports a simple text message to kick players with.

A yaml or properties file in the config directory for message configuration or translation would be nice but would require a decent combination of messages translated by the client, messages translated by the server based on the client's specified locale, and messages customized to override translation.

Out of curiosity, what messages in particular are you looking to customize?

**Comment by Xesau** [comment]
1. Stop
2. Restart
3. Kick/ban for the vanilla commands
4. And so forth

**Comment by dredhorse** [comment]
shouldn't [message changer lite](http://dev.bukkit.org/bukkit-plugins/messagechangerlite/) work on glowstone too?

**Comment by SpaceManiac** [comment]
The stop message is supposed to be configurable in `glowstone.yml` under the key `server.shutdown-message` but this functionality is currently broken. I'll be sure to fix that before marking this fixed, at minimum. But give the mentioned plugin a try and let me know if it covers the important use cases (there are some situations Glowstone doesn't fire the right events for, but they're infrequent).

**Comment by JeromSar** [comment]
@SpaceManiac is the issue now fixed?

**Comment by SpaceManiac** [comment]
I'm considering this fixed for now. Re-file if problems persist.
