### ISSUE TITLE
Glowstone license does not comply with Bukkit license

### ISSUE THREAD

**Issue by Grinch** [GlowstoneMC/Glowstone-Legacy#147]
~~As discussed in #glowstone, it has been determined that Glowstone's MIT license is not valid due to it implementing and bundling Bukkit. This means that Glowstone must become GPLv3 in order to comply with Bukkit's license.~~

Consensus has been: Glowstone's _distribution_ ("the software as it is actually run") must be licensed under the GPL. The source code can remain MIT. This ticket will be closed when the distribution includes a copy of the GPL.

Reference: http://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

**Comment by JeromSar** [comment]
@Grinch has a valid point. :)

**Comment by Ribesg** [comment]
At first I was like "But MIT is GPL-Compatible", but Google says it only means you can use MIT things in GPL things, not the other way

**Comment by gdude2002** [comment]
GPL makes me sad. It's like a frickin' headcrab.

**Comment by dumptruckman** [comment]
Yeah... Just go GPLv3 and then don't take it out on plugins when they don't go GPLv3. :)

**Comment by JeromSar** [comment]
@dumptruckman Bukkit is not included in plugins and thus these restrictions don't apply to them.

**Comment by Ribesg** [comment]
Yeah but plugins can't exist at runtime without Bukkit

**Comment by gdude2002** [comment]
It's a sticky and confusing situation, but it might be **safer** to assume that the GPL does apply to plugins unless someone can get a code lawyer to say otherwise.

**Comment by Grinch** [comment]
The tricky part is that gnu.org states that it is included and therefore must comply, but it isn't included. Even if it doesn't work outside of the Bukkit environment it can be compiled and redistributed without ever including it in the same file.

**Comment by JeromSar** [comment]
@Grinch is correct.

**Comment by Zidane** [comment]
GPL is an infectious license basically this is how Glowstone/Bukkit developers become "legal"

Glowstone: License becomes GPL v3, same as Bukkit
Plugin Developers: License becomes GPL v3, same as Bukkit

There is no ifs ands or buts, the verbage is clear. If you use a GPL lib a part of your implementation then you must be GPL as well. Glowstone and Plugin Developers both MUST use this license to be in compliance.

Welcome to the "Open Source" movement.

**Comment by JeromSar** [comment]
GPL references "libraries" as libraries _included_ in the distribution. Plugins reference libraries and don't include them and are thus free of imposed restrictions. Glowstone on the other hand _does_ include Bukkit and thus must comply to the GPL license.

The discussion is irrelevant, this issue is directed towards Glowstone, not plugins.

**Comment by Ribesg** [comment]
"Plugins don't include them"

You missed some gems on DBO :p

**Comment by Zidane** [comment]
@JeromSar 

If a program released under the GPL uses plug-ins, what are the requirements for the licenses of a plug-in?

It depends on how the program invokes its plug-ins. If the program uses fork and exec to invoke plug-ins, then the plug-ins are separate programs, so the license for the main program makes no requirements for them.

If the program dynamically links plug-ins, and they make function calls to each other and share data structures, we believe they form a single program, which must be treated as an extension of both the main program and the plug-ins. This means the plug-ins must be released under the GPL or a GPL-compatible free software license, and that the terms of the GPL must be followed when those plug-ins are distributed.

If the program dynamically links plug-ins, but the communication between them is limited to invoking the ‘main’ function of the plug-in with some options and waiting for it to return, that is a borderline case. 

Bukkit plugins fit the second paragraph, not the third

https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#TOCGPLAndPlugins

http://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins (GPL v3)

**Comment by Raphfrk** [comment]
GPL only requires that you open source your code.  

You don't need to actually release it under GPL, as long as the license gives users at least as many rights as GPL would.  

MIT gives more rights than GPL, so you don't need to change it.

**Comment by mokou** [comment]
@Raphfrk is correct. Glowstone can stay licensed as is. This issue was created under the false assumption that the MIT license is GPL-incompatible. The [MIT license](http://en.wikipedia.org/wiki/MIT_License) is [GPL-compatible](http://www.gnu.org/licenses/license-list.html#Expat).

**Comment by gdude2002** [comment]
So.. Is this resolved, then?

**Comment by JeromSar** [comment]
@SpaceManiac This can be closed now. :)
