### ISSUE TITLE
Clients can connect more than once

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#150]
Yesterday while testing Glowstone I found out this issue, I'm not sure how to replicate it (or if it can actually be replicated) but apparently trying to connect with my minecraft client ended up in connecting three times for some reason

```
2014/09/03 23:06:21 [INFORMACIÓN] Konato_K [/127.0.0.1:54589] connected, UUID: 11697c28-9c63-31ba-8f90-07e3c49c59d2
2014/09/03 23:06:21 [INFORMACIÓN] §eKonato_K joined the game
2014/09/03 23:06:23 [INFORMACIÓN] Konato_K [/127.0.0.1:54590] connected, UUID: 11697c28-9c63-31ba-8f90-07e3c49c59d2
2014/09/03 23:06:23 [INFORMACIÓN] §eKonato_K joined the game
2014/09/03 23:06:25 [INFORMACIÓN] Konato_K [/127.0.0.1:54591] connected, UUID: 11697c28-9c63-31ba-8f90-07e3c49c59d2
2014/09/03 23:06:26 [INFORMACIÓN] §eKonato_K joined the game
```

This appeared on the chat and on the client it looked like this
![Image](http://i.imgur.com/9Qrz8A1.png)

As you can see there are 3 of me, one being me (the camera) another being a player that never moved, and the other being another copy of me that followed what I was doing (with a slightly delay, that's why you can see it's head), this happened with build 46, but I didn't found any changes about this for 47 so I think it still may be valid, as a note I only opened one client, but for some reason it connected 3 times, if you want to see the full log it's [here](http://pastebin.com/VgbAQhTy)

**Comment by JeromSar** [comment]
Looking into this.

**Comment by JeromSar** [comment]
I believe I fixed the problem but I cannot test due to #145.  When the issue is resolve, I'll hopefully submit a PR with a patch. :)

**Comment by SpaceManiac** [comment]
Was this produced with a single MC client open, and a single connection to the server made? Did you cancel while connecting and then connect again, or anything like that?

**Comment by ghost** [comment]
It was a single client, I didn't open more than one, and I tried to connect after disconnecting (as the full log shows) and for some reason it logged three times, I didn't cancel the connection.
