### ISSUE TITLE
Show held items of players

### ISSUE THREAD

**Issue by Phreyr** [GlowstoneMC/Glowstone-Legacy#164]
Currently you can only see your own item client-side. Other players do not see it, and vice versa.

**Comment by Lar095070** [comment]
I would like to note that even though this is a working server jar, it is not complete and not everything works

**Comment by Phreyr** [comment]
@Lar095070, I never said everything was expected to work. I'm just logging a bug that should be solved at some point.

**Comment by Lar095070** [comment]
i was just noting that

**Comment by se1by** [comment]
Just wanted to say that it seems to me that we aren't sending that packet http://wiki.vg/Protocol#Held_Item_Change
Didn't verified that though

EDIT:
In reaction to this packet: http://wiki.vg/Protocol#Held_Item_Change_2

**Comment by SpaceManiac** [comment]
The mentioned packet is used to tell the client which item slot (0..8) in its hotbar it has selected. Play-out-0x04 Entity Equipment is used to display equipment such as item in hand.
