### ISSUE TITLE
Filter invalid items types

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#168]
Many block types (water, lit lamp, portal) are now invalid as items and should be filtered out somehow, because they crash the client. Also they may get stuck in the inventory and crash indefinitely. So this is important.

**Comment by ZachBora** [comment]
Also noticed you could give the client wool with data of 35 (35:35), it gives the client a block named Wool without a texture (purple and block squares). Placing the block puts a while wool and raises an error of invalid data.

```
09:21:19 [SEVERE] Error while handling BlockPlacementMessage{x=6, y=64, z=-7, direction=1,
 heldItem=ItemStack{WOOL x 1}, cursorX=8, cursorY=16, cursorZ=9} (handler: BlockPlacementHandler)
java.lang.IllegalArgumentException: Metadata out of range: 35
        at net.glowstone.GlowChunk.setMetaData(GlowChunk.java:471)
        at net.glowstone.block.GlowBlock.setTypeIdAndData(GlowBlock.java:173)
```

**Comment by PaulBGD** [comment]
How would we handle this? The best way I can think of is just replacing the id with air or something when you try to grab it.

**Comment by turt2live** [comment]
Weird things happen when you take #417, #267, and #360 on a single server too. 

http://i.turt2live.com/OHJY.jpg

**Comment by gdude2002** [comment]
I'm pretty sure that would happen without #360 anyway :P

**Comment by fmgez123** [comment]
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/GlowChunk.java
the if statement on line 501 is what throws the 'metadata out of range', but it fails to do anything about the error and still tries to set the items meta to an invalid value.  Either a return is needed after the exception, or set a default value of 0 would be reasonable.  I would offer a PR but I am still just learning about the project.

**Comment by fmgez123** [comment]
section.types[index] = (char) ((type & 0xfff0) | metaData);

And while I am looking, I am not understanding this last line of the same. I think I am going to look stupid, but forgive me asking. 'type' is the existing metaData value of this block, and 'metaData' is the new value that we are attempting to assign to this index, but the '|' is an OR operator? In this situation an OR does not appear to be what is wanted, as this is a setter for metaData. Sorry if I am totally missing something, I want to help, but still have a lot of learning to do on my own.

**Comment by SpaceManiac** [comment]
@fmgez123 
The `types` array combines the type and metadata values. Each block has one entry in the array. The top 12 bits (`0xfff0`) are the type, and the bottom four bits (`0xf`) are the metadata.

**Comment by fmgez123** [comment]
Understood.  Thanks for the clarification.  My first post still applies to the situation I think.
