### ISSUE TITLE
Add russian language support.

### ISSUE THREAD

**Issue by Leymooo** [GlowstoneMC/Glowstone-Legacy#169]
screenshot in game: http://i.gyazo.com/df0aa05847ef09390c231360e37c97f4.png
http://i.gyazo.com/c86e0c08ecc44a744a7250abd2066053.png
In console: http://i.gyazo.com/dcc2b7501791fca624c39a80d199da38.png
Ty. When I write in Russian in the game, it is not displayed. 
When I write in English, it is displayed. 
Fix it.

**Comment by EntityReborn** [comment]
Demanding something be fixed is a sure way to have your issue triaged as low as possible.

**Comment by SpaceManiac** [comment]
The problem here is the chat formatted/wrapper, I think, which filters out characters it doesn't know the width of. It needs improvement (see #86).

**Comment by turt2live** [comment]
Fixed via https://github.com/GlowstoneMC/Glowstone/commit/d5a1f56f50b35f7f3950cb3772940662c18bf0b0
