### ISSUE TITLE
New License

### ISSUE THREAD

**Issue by zyuiop** [GlowstoneMC/Glowstone-Legacy#188]
It would be greate to use a GNU GPL license for the project, or at least a LGPL, because the license you use isn't realy complete and the developers' rights aren't mentioned.

**Comment by JeromSar** [comment]
See #147 and #148. It was decided that GlowStone is sticking with MIT for now. :)

**Comment by zyuiop** [comment]
Sorry, didn't noticed that. But I wasn't on IRC, si what is the reason Of your choice ?

**Comment by JeromSar** [comment]
@zyuiop Currently, we want to be as permissive with the license as possible. Bukkit's GPL license only forces us to license the jar under GPL, but not the source.

**Comment by SpaceManiac** [comment]
Closed - duplicates the tickets mentioned, see them for further information on licensing.
