### ISSUE TITLE
AsyncPlayerChatEvent not working

### ISSUE THREAD

**Issue by LukeFlynn** [GlowstoneMC/Glowstone-Legacy#199]
Hey! I'd just like to report that when I try using AsyncChatEvent in a plugin it simply doesn't work, however using the older PlayerChatEvent does.

**Comment by RhvsW** [comment]
Not implemented in master branch, use bungee branch for it.

**Comment by LukeFlynn** [comment]
Mmkay, thanks. :)

**Comment by ZachBora** [comment]
also this is a dupe of #103

**Comment by SpaceManiac** [comment]
Closed as dupe, thanks for the help anyways though!
