### ISSUE TITLE
Diamonds on 45 Y Coord

### ISSUE THREAD

**Issue by Polowicer** [GlowstoneMC/Glowstone-Legacy#204]
Hello! I just found diamonds on 45 Y Coord, it should be fixed ;>
Thanks!

**Comment by RhvsW** [comment]
Worldgen is not fully implemented yet. There is probably a dupe ticket for wgen somewhere.

**Comment by SpaceManiac** [comment]
Thanks for the report! Refer to #76 for what is currently planned to fix this and other wgen issues.
