### ISSUE TITLE
Pick block not working for all blocks

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#205]
Known cases:
- Lit redstone ore (you can pick the non-lit version, but step on it and pick it causes issues)

**Comment by stuntguy3000** [comment]
- Command Blocks

**Comment by iamgreaser** [comment]
Lit RS ore is GLOWING_REDSTONE_ORE, as opposed to REDSTONE_ORE.

Check src/main/java/net/glowstone/block/ItemTable.java for this line:

```
        reg(Material.REDSTONE_ORE, new BlockRandomDrops(Material.REDSTONE, 0, 3, 4));
```

and add this after it:

```
        reg(Material.GLOWING_REDSTONE_ORE, new BlockRandomDrops(Material.REDSTONE, 0, 3, 4));
```

If you're having issues with charged redstone _dust_, or unlit redstone _torches_, or even regular torches, those work fine in the RS PR ( #215 ).

For command blocks, they are Material.COMMAND. I'm not sure what you have to do to get them to work.

**Comment by turt2live** [comment]
@iamgreaser this is not the drops, this is the pick block key.

**Comment by turt2live** [comment]
Looking into this further (but not very deeply) came up with this information:

It appears as though the pick block is handled client-side but the client just tells the server "oh, by the way, add <item> to my inventory. Thanks!" instead of having the server validate the logic. More investigation should be done though

**Comment by dequis** [comment]
Is this ticket about creative or survival?

**Comment by turt2live** [comment]
@dequis creative..............................

**Comment by dequis** [comment]
```
18:40 <+turt2live> dx : I'm going to hit you
18:40 < dx> turt2live: what
18:40 < dx> WHAT DID I DO
18:40 <+turt2live> dx : Asked a dumb question
18:41 < dx> turt2live: ;_;
18:41 <+turt2live> I answered your dumb question <3
18:41 < dx> turt2live: but it's entirely possible to have issues with middle click in survival
18:42 < dx> it did behave weirdly when i tested it
18:42 < dx> with heads
18:42 <+turt2live> oh right
18:42 <+turt2live> forgot about that
18:42 <+turt2live> I'll test that later
18:42 < dx> see, not dumb!
18:42 < g> slightly dumb
18:42 < g> maybe
```

**Comment by turt2live** [comment]
._.

**Comment by Tonodus** [comment]
Picking command blocks works well on latest Glowstone, Lit Redstone Ore seems to be not pickable at all, even in vanilla Mc.
I agree, picking seems to be 100% client side: "Note that middle-click in creative mode is interpreted by the client and sent as a Creative Inventory Action packet instead." (wiki.vg). Therefor this might be closed.

**Comment by SpaceManiac** [comment]
The pick block functionality is entirely client-side, so there's nothing we can do except investigate individual broken cases. If such a case arises (a block is pickable in vanilla SP/MP but not in Glowstone), it can be investigated then.
