### ISSUE TITLE
Chat text wrapping to next line without splitting words in half

### ISSUE THREAD

**Issue by lukespragg** [GlowstoneMC/Glowstone-Legacy#21]
I'd love to see this implemented so there is no need for a plugin. I hate seeing words cut off and having a letter or 2 on the next line. This should be something that should have been in Minecraft originally.

An indentation option would be neat too. I personally like indenting my text, but others may not.

**Comment by SpaceManiac** [comment]
Added in d6085b1fb75944d99959ad918d59c63311ceeb75. No indentation or non-word-splitting, just an emulation of what CraftBukkit does.

**Comment by lukespragg** [comment]
The whole idea was to NOT split the words. Is that what you mean? Splitting words is what I'd like to NOT have. I'd rather keep the word in one piece.

**Comment by SpaceManiac** [comment]
I plan to add it as an option in the future; just putting the commit here because it's relevant. (Also why I didn't close the issue)

**Comment by lukespragg** [comment]
Oh okay, why an option? People actually LIKE having their words cut off? :P

**Comment by SpaceManiac** [comment]
Covered in #86.
