### ISSUE TITLE
The Future of Glowstone

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone-Legacy#212]
In light of Sponge, are we just going to continue as we have been doing, or are we going to have to make way for a whole new community?

By that I mean, will our objectives change? Will our code have to cater to Sponge?

**Comment by SonarBeserk** [comment]
I dont think having only a single strong project would be good. Bukkit's fall showed a perfect example of that.

**Comment by ZephireNZ** [comment]
If Bukkit and the plugins that use it die out, as some are expecting, it could be a good idea to work towards implementing the Sponge API (or whatever becomes popular). 

Perhaps have the core code of Glowstone, and then have the different API implementations on top of that? Similar to how WorldEdit does it (it has implementations for Bukkit, Forge, and LiteLoader).

**Comment by mastercoms** [comment]
I guess we can have the core code and then have a Bukkit/Sponge bridge, or we can do it how Spout did it (support generic voxel games, and add a Minecraft bridge, and then a Bukkit bridge on top of that), but that would take a lot of rewriting.

Or, we could provide/help Sponge with Bukkit API abstraction or something.

Or, as @SonarBeserk said, we could just continue as we have been doing, acting as a backup if Sponge becomes the main thing.

**Comment by turt2live** [comment]
Relevant: https://github.com/SpaceManiac/Glowstone/issues/219

**Comment by gdude2002** [comment]
The only problem with using Sponge as a "backup" is that it would require a Bukkit <-> Sponge abstraction to get it implemented within any reasonable amount of time, unless Glowstone is already being build to support multiple APIs. So, regardless of what we're actually going to do, we should look into that possibility early.

**Comment by mastercoms** [comment]
Pore is an interesting project looking to bridge Sponge and Bukkit.
http://www.reddit.com/r/spongeproject/comments/2frfaa/pore_a_bridge_for_bukkit_and_sponge/

**Comment by espidev** [comment]
Just continue glowstone i guess.

**Comment by SpaceManiac** [comment]
Glowstone is continuing; Sponge support will happen eventually. Considering this ticket resolved.
