### ISSUE TITLE
Opening fence gate with block in hand places block

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone-Legacy#213]
When right clicking on a fence gate with a block in hand, the block is placed as well. This should just open the fence gate, and not place the block.

**Comment by turt2live** [comment]
https://github.com/SpaceManiac/Glowstone/pull/200 relevant

**Comment by daboross** [comment]
Awesome, thanks for pointing that out. I didn't see that when looking over open issues.

**Comment by daboross** [comment]
Oh, that's a PR. :D

**Comment by turt2live** [comment]
Created a parent ticket for similar issues related to interaction of blocks: #325
