### ISSUE TITLE
Swords break blocks while in creative mode

### ISSUE THREAD

**Issue by squidicuzz** [GlowstoneMC/Glowstone-Legacy#214]
When in creative mode, you can break blocks while using a sword.

**Comment by mastercoms** [comment]
Could someone give me any pointers to where block breaking by a player happens? 
Is it GlowBlock.breakNaturally(ItemStack tool)?

**Comment by TomCaserta** [comment]
I believe its in net.glowstone.net.handler.play.player.DiggingHandler the actual breaking of the block.

**Comment by Johni0702** [comment]
Determining whether it is an insta-break is done in net.glowstone.EventFactory.onBlockDamage (line 159) which is called by the DiggingHandler

**Comment by mastercoms** [comment]
Alright, thanks!
