### ISSUE TITLE
Drop the Bukkit API

### ISSUE THREAD

**Issue by worksofliam** [GlowstoneMC/Glowstone-Legacy#217]
Coming from Bukkit (since 2011) and seeing this brings a smile to my face, but honestly I think you need to drop the Bukkit API out of this project; all it's doing is piling work on top of everyone who contributes to this project and Bukkit changes all the time.. and no one would always want to be on top of that.

This is just my opinion, but it looks like a lot of work is being put into this.. I will try and help but I'm also working full time so I will try my best in my free time.

**Comment by greatman** [comment]
Bukkit API is very stable.

**Comment by Ribesg** [comment]
This project is essentially an implementation of the Bukkit API. Dropping it makes no sense.

I'm strongly against this, as a lot of people are. Bukkit is the strongest, most stable API I've ever seen. Ever.

**Comment by gdude2002** [comment]
Yeah, this ticket really makes no sense. There are nothing but advantages to be had from using the Bukkit API. This is really the entire point of Glowstone - A clean-room implementation of a Bukkit-based server.

**Comment by worksofliam** [comment]
I know that Bukkit is best at what it does, but as it updates is Glowstone going to be able to stay on top of it stably?

**Comment by mastercoms** [comment]
Yep, it doesn't use any NMS code or decompiled code so we shouldn't into any problems.

Plus, we could the Spout API in the future if anything really bad happened.

**Comment by worksofliam** [comment]
Thank you mastercoms, may as well close now.
