### ISSUE TITLE
Decide if Glowstone should implement SpongeAPI

### ISSUE THREAD

**Issue by Ribesg** [GlowstoneMC/Glowstone-Legacy#219]
Obviously, it would be good to wait for some APIs to be defined, at all. Because of this, this issue should have a low priority for now.

https://github.com/SpongePowered/SpongeAPI

Implementing it would allow more individuals to be involved and would just extend the amount of plugins supported, actually making Glowstone better than Sponge on that part.

On the other hand, Sponge will certainly implement some kind of Forge mods sending to the client or something, not sure about this yet. This may not be possible / wanted for Glowstone.

Thoughts?

**Comment by gdude2002** [comment]
Sponge has stated that their API will at least be compatible with Glowstone and that they intend on forking Glowstone to add support for it - Obviously, this would be much better to do ourselves.

I think the possibility of supporting multiple APIs would put us streets ahead of the competition, though.

**Comment by mastercoms** [comment]
@gdude2002 yes, making glowstone the universal server for all apis would be great.

**Comment by SpaceManiac** [comment]
Glowstone **will** implement SpongeAPI in some form or another (specifics of implementation indeterminate) at some point in the future, probably once SpongeAPI is at a point where it's actually worth implementing (which it will be soon... branch time anyone?).

**Comment by SpaceManiac** [comment]
Considering this resolved since the decision has been made. Can open a new ticket for the actual Sponge support itself when the time is right.
