### ISSUE TITLE
Support for language translations of server messages

### ISSUE THREAD

**Issue by lukespragg** [GlowstoneMC/Glowstone-Legacy#22]
Can be stored in /messages/languagecode.yml, /messages/Language.yml, or in a subdirectory under config for example.
Strings such as "Server shutting down." would be able to be translated for those running region specific servers.

**Comment by SpaceManiac** [comment]
Pushed a little bit of stuff to the 'language' branch. May work on this more later.

**Comment by SpaceManiac** [comment]
Covered in #86.
