### ISSUE TITLE
PlayerMoveEvent is not called

### ISSUE THREAD

**Issue by witchica** [GlowstoneMC/Glowstone-Legacy#222]
Hi, great work, I am really loving watching the progress here, but I have one question, does PlayerMoveEvent ever get called? My plugin relies on it but it does not seem to be working, and I was wondering if it was a fault on my end, or whether Glowstone does not have that yet. Thanks! :)

**Comment by turt2live** [comment]
No

**Comment by witchica** [comment]
Ok, thanks for telling me :)

**Comment by turt2live** [comment]
But keeping this ticket open will server as a reminder :P

On Mon, Sep 8, 2014 at 10:59 AM, tattyseal notifications@github.com wrote:

> Ok, thanks for telling me :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpaceManiac/Glowstone/issues/222#issuecomment-54851833
> .

## 

Sincerely,
Travis R

(Turt2Live http://turt2live.com/)

**Comment by witchica** [comment]
I might look into making a pull request for it :+1:

**Comment by SpaceManiac** [comment]
I just checked and no. Leaving this open as a reminder.

**Comment by JeromSar** [comment]
Working on this.

**Comment by turt2live** [comment]
Relevant parent: #28

**Comment by turt2live** [comment]
Closing. #28 is suitable enough.
