### ISSUE TITLE
UUIDs for players who have never joined don't get fetched

### ISSUE THREAD

**Issue by vurpo** [GlowstoneMC/Glowstone-Legacy#227]
When one tries to ban or op a player who has never joined, the server doesn't fetch the real online UUID to add to the `config/banned-players.json` or `config/ops.json` files. This results in those players not getting banned or opped.

**Comment by turt2live** [comment]
Is your server in offline mode?

**Comment by vurpo** [comment]
No, it's in online mode. If i op myself before ever joining, then join, then op myself again, there will be two entries with my name in ops.json. One with the wrong UUID and one with the correct one.

**Comment by turt2live** [comment]
What are the uuids?

sent from mobile

**Comment by SpaceManiac** [comment]
Glowstone doesn't look up UUIDs with Mojang except during player login. So if you `/op bob`, and the server has never seen a player with name `bob`, it ops the offline-mode UUID of `bob` instead... kind of weird design, probably worth fixing.
