### ISSUE TITLE
When using a /item command through a plugin, items do not stack

### ISSUE THREAD

**Issue by lukespragg** [GlowstoneMC/Glowstone-Legacy#23]
Items fill the inventory AND equipment slots instead of stacking like they should regardless of the type of item they are.

The native /give command works fine though. Perhaps just an issue with the plugin compatibility.

**Comment by SpaceManiac** [comment]
Could you give more info? What did your inventory look like before, what command line did you use, and what did it look like after?

**Comment by lukespragg** [comment]
I had nothing in my inventory, used an item command to get the default stack of 64 which I had set in CommandBook.
I believe the server also defaults to 64 with the /give command?
After using the command, the inventory, quickslots, AND armor slots were filled with apples, axes, swords, anything I tested with.

Coal seems to work fine though... O_o  I haven't tested with every item yet.

Edit: The issue seems to only occur with 3 digit items. All blocks seem to be fine.

**Comment by SpaceManiac** [comment]
Please let me know what the results are with Book (340) and Snowball (332). If I had to guess, Glowstone is just obeying the maximum stack sizes a little more thoroughly than CraftBukkit.

**Comment by lukespragg** [comment]
Ahh, books stack fine and snowballs form stacks of 16 when out of 64.

**Comment by SpaceManiac** [comment]
Suspicion confirmed; I'll fix this up eventually.

**Comment by SpaceManiac** [comment]
For now, not a bug. I'll fix it up if it becomes an issue later.
