### ISSUE TITLE
Head

### ISSUE THREAD

**Issue by IPFaN** [GlowstoneMC/Glowstone-Legacy#230]
I no see my head, hmm i see only dark from my skin..

**Comment by gdude2002** [comment]
Can you please elaborate and perhaps provide screenshots?

**Comment by IPFaN** [comment]
I see https://minotar.net/avatar/IPFaN/100.png,
but i need to se..
https://minotar.net/helm/IPFaN/100.png

**Comment by EntityReborn** [comment]
@IPFaN, this is a known issue already.
@gdude2002, he means the second head layer isn't being displayed.

**Comment by SpaceManiac** [comment]
I appreciate the report - see #162.
