### ISSUE TITLE
Remapping support

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#238]
Make use of [OverMapped](https://github.com/Wolvereness/OverMapped) or a similar tool for Gradle to remap `_INVALID_*` methods in the Bukkit API over their non-deprecated counterparts as part of the build, like CraftBukkit does.

Ignored for a while since every `_INVALID` method was using missing functionality, but this is needed to update to newest Glowkit in order to support the `getOnlinePlayers` change without a _lot_ of breakage.

Resist the temptation to copy CraftBukkit's list of overmapped methods; the list should be fairly easy to generate from a search on Bukkit itself.

**Comment by dequis** [comment]
427b9e13d9f9f7f3c40987ad802ea9081b498d63 - Close this?
