### ISSUE TITLE
Connection Lost #56 build

### ISSUE THREAD

**Issue by Leymooo** [GlowstoneMC/Glowstone-Legacy#239]
![](http://i.gyazo.com/f866440f9d4ba7d8776099a45ce04647.png)

**Comment by SpaceManiac** [comment]
turt2live reports:
- Problem with fresh world on 56 build - corrects itself after restart
- World generated on 56 & run on 55 or vice versa has no problems.

More screenshots:
![Wombosvideo](http://puu.sh/brY8H/705e0d039a.png)
![turt2live](http://i.turt2live.com/P34q.png)
![gDude](https://i.imgur.com/Um3wvfC.png)

**Comment by turt2live** [comment]
Another screenshot:

![image](https://cloud.githubusercontent.com/assets/1190097/4206374/74a9f0ec-384a-11e4-850f-c8b430d68f72.png)
