### ISSUE TITLE
`kicked: Timed out` keeps being broadcasted after player has left, and `list` shows 0 players online.

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone-Legacy#243]
Here is the full log: http://qx.lc/FQQ9.text

At the end of the file, you'll see `dabo043 kicked: Timed out` keeps being shown after all players have left, and `list` shows 0/100 online.

**Comment by turt2live** [comment]
Steps to reproduce?

**Comment by daboross** [comment]
I am unsure about steps yet, what I did to get that was just connect with 83 different clients, then disconnect them all in one second. I guess I can close this until I can come up with a way to reliably reproduce.
