### ISSUE TITLE
Bows don't shoot arrows

### ISSUE THREAD

**Issue by walterhiggins** [GlowstoneMC/Glowstone-Legacy#248]
Arrows can't be shot from bows.
In Creative Mode, I draw a bow (infinite arrows since I'm in creative mode) and release but when I release, the arrow is not released. It just disappears.

**Comment by greatman** [comment]
Entities are currently being implemented, hence why arrows don't spawn ;)

**Comment by gdude2002** [comment]
#4, #139

**Comment by walterhiggins** [comment]
Thanks for the quick response. Am unfamiliar with bukkit internals but let me know if I can help with this effort. Really impressed that ScriptCraft bukkit plugin works ootb with Glowstone.

**Comment by greatman** [comment]
Everything is open-source, you are free to help ;)
