### ISSUE TITLE
Can't use Shopkeepers plugin

### ISSUE THREAD

**Issue by laurentdu51** [GlowstoneMC/Glowstone-Legacy#254]
Hello, i'm try to use this plugin with Glowstone serveur but i'm have this error.

10:15:30 [INFOS] [Shopkeepers] Enabling Shopkeepers v1.25
10:15:31 [GRAVE] [Shopkeepers] Potentially incompatible server version: glowstone
10:15:31 [GRAVE] [Shopkeepers] Shopkeepers is trying to run in 'compatibility mode'.
10:15:31 [INFOS] [Shopkeepers] Check for updates at http://dev.bukkit.org/bukkit-plugins/shopkeepers/
10:15:31 [GRAVE] [Shopkeepers] Incompatible server version: Shopkeepers cannot be enabled.

Plugin info : http://dev.bukkit.org/bukkit-plugins/shopkeepers/

**Comment by Aaron1011** [comment]
@laurentdu51: Glowstone still doesn't implement large chunks of the Bukkit API. Thus, some plugins will work, but others (especially anything dealing with entites) will break.

Shopkeepers won't work at all until Glowstone has better entity support, and supports Villagers.

**Comment by turt2live** [comment]
This particular plugin doesn't correctly check for Glowstone. Please contact the author.
