### ISSUE TITLE
Use of Logger is not Standard

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone-Legacy#255]
In the code, the use of logger varies from logger.log(level, message) and logger.level(message).
Should I make a pull request changing all logger requests to logger.log(level, message)?
Or does it not matter?

**Comment by JeromSar** [comment]
Usually, when the message is solely text, `logger.level(String)` should be used. However, when the message consists of various parts, using `logger.log(Level, String, Object...)` is more efficient. Concatenation is faster this way.

**Comment by turt2live** [comment]
Concatenation is not any faster. If you can provide valid proof of that, I'll believe you.

**Comment by mastercoms** [comment]
@turt2live Actually I found out that using logger.level(String) is faster on modern Java compilers. With logger.log(Level, String, Object) has to be parsed and is actually more inefficient. Back in the day, all those Strings would create new objects which would hurt performance but now the compiler knows to use StringBuilder, so logger.level(String) is faster.

But it still raises the question, should we replace all our logger requests to one way?

**Comment by turt2live** [comment]
You'll still need to provide evidence that one is faster over the other. Claims don't stand up without proof :P

**Comment by SpaceManiac** [comment]
For errors, `log(Level, String, Exception)` is used.
For messages with no exception attached, `level(String)` is used.
I plan to fix cases where this is inconsistent.

**Comment by mastercoms** [comment]
@SpaceManiac Alright, I'll fix that in the ShutdownMonitorThread since I'm fixing the rogue thread killer in my commit anyway.
