### ISSUE TITLE
Missing entity ?

### ISSUE THREAD

**Issue by laurentdu51** [GlowstoneMC/Glowstone-Legacy#256]
Hello, 

I'm try to load an 1.8 world and i'm have this error in log.
This is missing entity in the server ? 
http://pastebin.com/PnCpRy1U

**Comment by Aaron1011** [comment]
@laurentdu51: Glowstone currently has very little support for entities. The error you got was because a `Pig` was saved in the world, but Glowstone can't handle it.

**Comment by turt2live** [comment]
See issue #139. Closed as duplicate. Thanks for the report!
