### ISSUE TITLE
Placed torches are not being saved

### ISSUE THREAD

**Issue by Merlinn** [GlowstoneMC/Glowstone-Legacy#257]
... even if doing /save-all

**Comment by turt2live** [comment]
Related to #119

**Comment by SpaceManiac** [comment]
Did some testing, this is a placement handling issue (see turt's comment), not a world I/O issue. Torches placed don't get their data value set, so they're zero internally, which is a no-good value and the torches are invisible. #215 has a fix for torch placement.

**Comment by SpaceManiac** [comment]
Fixed in 0a659d02.
