### ISSUE TITLE
Impossible to add enchantments to items via API

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone-Legacy#262]
No enchantments are registered on `org.bukkit.enchantments.Enchantment`, thus `Enchantment.getByName()` or `Enchantment.getById()` will always return null.

I don't know if enchantments are implemented at all regularly, I'm just opening this for the API compatibility side of it.

**Comment by dequis** [comment]
So this is the like #295 (fixed in 64345cd599313dfcdfc3db39d893658eed560ee8), but for enchantments instead of potions
