### ISSUE TITLE
Skulls are not properly implemented

### ISSUE THREAD

**Issue by Aaron1011** [GlowstoneMC/Glowstone-Legacy#266]
Currently, attempting to place any type of skull (Player, Zombie, Wither Skeleton, Skeleton, or Creeper) will result in a Skeleton head being placed, always facing the same direction.

**Comment by ZephireNZ** [comment]
This is part of a larger issue, each item that has rotation etc need to be handled, see #119.

**Comment by turt2live** [comment]
Closed as duplicate
