### ISSUE TITLE
[Minor] Worlds take half an eternity to save

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#270]
It's minor, but in Vanilla/CraftBukkit it's not 3-15 seconds per world.

**Comment by ZephireNZ** [comment]
I've been noticing it as well, so it's not just on one machine.

**Comment by dequis** [comment]
Good thing these are not production servers, because I always ctrl-c the fuck out of it.

**Comment by SpaceManiac** [comment]
Keeping height maps in a1a7fc7a3f9fffe62f54a205f0cf851a7111bed8 improved world save times by a decent amount. From investigation, using `DEFLATER.BEST_SPEED` for compression improves world save times even further, but I need to check more real-world use cases to make sure this doesn't have implications for world size. Switching the entire RegionFile/NBT stack to use Java NIO yielded essentially no improvement in my tests.

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
