### ISSUE TITLE
BlockPlaceEvent always reports AIR as the placed block

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#271]
This ticket was originally about CoreProtect, but it's more general than that.

The event handlers of BlockPlaceEvent receive an AIR block, so they have no way to know what block was placed. In the case of CoreProtect, this means block placement doesn't get logged.

The other issue has been split to #273

---

_The original description follows_

```
- [x] Block break in survival
- [ ] Block place in survival
- [ ] Block break in creative
- [ ] Block place in creative
```

Chat logging isn't working either, but that's #103. Also the other events mentioned in the coreprotect bukkitdev page don't seem to apply yet to our current feature set.

Note that CoreProtect needs sqlite to start, use this commandline:

```
java -cp glowstone.jar:sqlite-jdbc-3.7.2.jar net.glowstone.GlowServer
```

**Comment by dequis** [comment]
Wrote a shitty test plugin - http://dequis.org/block-place-break.jar

BlockPlaceEvent always reports AIR for the block type regardless of game mode.

BlockBreakEvent doesn't fire in creative.

**Comment by dequis** [comment]
Split the issue in two, and updated description.

**Comment by SonarBeserk** [comment]
I have found that the vanilla client does not send the finish breaking packet when a player in creative which covers part of the issue. Im trying to see what can be done to fix this.
