### ISSUE TITLE
Red sandstone stairs and slabs are not fully functional

### ISSUE THREAD

**Issue by scooterboo** [GlowstoneMC/Glowstone-Legacy#285]
It should be an easy fix of coping code over form the stairs, slabs, and doubleslabs that work.

**Comment by Nickforall** [comment]
Started working on this, I have to edit Glowkit too

**Comment by Nickforall** [comment]
I'm stuck, I have no idea why it doesn't work, I can't place slabs with half:top.
- I have changed the Glowkit, and added a step2 class, like step and wood_step.
- tried to handle the bytes in the BlockSlab class

but both didn't worked out, I fixed the bug that the slabs couldn't stack and that stairs didn't work.

**Comment by Tonodus** [comment]
I don't understand you well, but the Stair class in bukkit has already methods like get/setFacing and is/setInverted(). You only have to use them and don't have to add a new class.

**Comment by Nickforall** [comment]
I used them, but there is a class that is used for the Material.Step and another one for Material.Wooden_step or something like that. But Material.Step_2 doesn't have one. Those classes have the Inverted methods.

**Comment by SpaceManiac** [comment]
As I understand, fixed in c061facfed82710dff442f96e35138a41048b4c0.
