### ISSUE TITLE
Plugin management (download/update).

### ISSUE THREAD

**Issue by greatman** [GlowstoneMC/Glowstone-Legacy#287]
Toby on IRC had the idea for server managers to have a package management system for plugins. Kinda like gem/apt-get

**Comment by ghost** [comment]
I have a concept for this sort of system ready as I was planning to implement plugin management for CraftBukkit in Python (using bugket).
I'll write some specifics down tomorrow, it's late over here.

**Comment by navarr** [comment]
might be interesting to investigate composer and take some of it's benefits, too.

**Comment by SpaceManiac** [comment]
What would be the advantages of implementing this in core over a plugin? Also, how would hosting, moderation, etc. go? Piggyback on maven (in which case see #143)?

**Comment by greatman** [comment]
A system similar to maven could do the job indeed.

**Comment by ghost** [comment]
I was thinking of something similar to Ruby gemfiles, e.g. a plugins.yml that can be easily checked into VC and gives the option to lock a plugin at a specific version if required (for example, due to compatibility issues).

It doesn't necessarily need to be in core, though I'd imagine it would provide some benefits in terms of security and ease of use for novice users.

**Comment by dequis** [comment]
> Also, how would hosting, moderation, etc. go?

I get the feeling this ticket is about a replacement to dev.bukkit.org...

**Comment by ghost** [comment]
> I get the feeling this ticket is about a replacement to dev.bukkit.org...

BukkitDev has no facilities for installing/updating plugins in an automated fashion, nor does it expose an API of any kind (as far as I'm aware). There's no unified system for updating, some plugins have builtin version checks and occasionally updaters, but nothing that could be described as easily maintainable, let alone VC-friendly.

**Comment by SpaceManiac** [comment]
There's a pretty subpar actual BukkitDev API, but there's this: http://bukget.org/

**Comment by dequis** [comment]
Oh btw, this is a bit tangential to the topic of this issue, but if anyone cares, here's a [dump](http://dequis.org/bukkitdev-releases.json.gz) (3.4mb compressed, 27mb uncompressed) of all the info from the [bukkitdev API](http://wiki.bukkit.org/ServerMods_API), which I got 11 days ago for the purpose of archiving all the plugin jars to [archive.org](http://web.archive.org/web/*/http://servermods.cursecdn.com/files/*). The file list that was parsed from that json file for archiving is [here](http://dequis.org/bukkitdev_all_file_urls.txt), it was 6gb total, 75494 files.

**Comment by ghost** [comment]
I think I'll go back to the idea of implementing it as a Python application. Kind of forgot that Bukget still works and will continue to do so after Craftbukkit came crashing down.

**Comment by SpaceManiac** [comment]
Closing since this is something that can be done on the plugin level pretty easily.
