### ISSUE TITLE
IP Binding

### ISSUE THREAD

**Issue by massl** [GlowstoneMC/Glowstone-Legacy#288]
Currently it is not possible to make the server listen only to one specific IP address (e.g. if the host system is multi-homed). Instead it binds to all configured IPs (0.0.0.0).

In a shared hosting environment it is needed to have the application bound to a specific IP address.

**Comment by SpaceManiac** [comment]
This _should_ be possible. `server.ip` in the config.

**Comment by massl** [comment]
It looks like it is working. Thank you!

I have edited the wiki https://github.com/GlowstoneMC/Glowstone/wiki/Configuration-Guide
Maybe someone can make that look more pretty - hah ;)
