### ISSUE TITLE
Doors and pressure plates don't activate

### ISSUE THREAD

**Issue by jwpwns** [GlowstoneMC/Glowstone-Legacy#290]
Not sure if this is known already but wood doors and iron doors don't work as well as pressure plates.

**Comment by Tonodus** [comment]
Well, Glowstone is still a work in progress. Ir on doors / pressure plates won't work, simply because there's no redstone in Glowstone currently. If I remembered right, someone's already working on doors.

**Comment by jwpwns** [comment]
ok

**Comment by turt2live** [comment]
Related to #325
