### ISSUE TITLE
Inventory addItem() drops ItemMeta

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#294]
`Aaron1011` on IRC reports that the `addItem` method in `GlowInventory` doesn't preserve item metadata (the ItemMeta attached to an item stack).

The manual ItemStack comparisons and creation should be replaced with uses of `isSimilar()` and `clone()`.

**Comment by ZephireNZ** [comment]
This was added into the code for #267 (I believe it was necessary to have skull items work properly). Either myself or Aaron1011 could make it into a seperate PR, if you'd prefer.

**Comment by turt2live** [comment]
(incoming late response) : Existing PR is fine. It's required to make that PR functional and the side effect is that it fixes another issue. I wouldn't complain about that ;)

**Comment by SpaceManiac** [comment]
This was fixed in 36d2bf0777a0fe8d374ae0d7a574982d721380ff.
