### ISSUE TITLE
org.bukkit.potion.PotionEffectType.getByName("SPEED") returns null instead of PotionEffectType[1, SPEED]

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#295]
Test case plugin: [jar](https://github.com/dequis/bukkit-plugin-test-cases/releases/download/PotionEffectType/Test-PotionEffectType.jar), [source](https://github.com/dequis/bukkit-plugin-test-cases/commit/PotionEffectType)

Type /command to test

Expected behavior (craftbukkit)

```
[05:35:55 INFO]: [Test] speed potion effect = PotionEffectType[1, SPEED]
```

Actual behavior:

```
05:35:22 [INFO] [Test] speed potion effect = null
```

Relevant bukkit source code:

https://github.com/GlowstoneMC/Glowkit/blob/master/src/main/java/org/bukkit/potion/PotionEffectType.java#L230

Found this one in the FirstJoinPlus plugin, when enabling apply-potion-effects, source:

https://github.com/chaseoes/FirstJoinPlus/blob/master/src/main/java/com/chaseoes/firstjoinplus/FirstJoinListener.java#L93

**Comment by Tonodus** [comment]
The related code of bukkit to be called:
https://github.com/GlowstoneMC/Glowkit/blob/master/src/main/java/org/bukkit/potion/PotionEffectType.java#L242
and afterwards https://github.com/GlowstoneMC/Glowkit/blob/master/src/main/java/org/bukkit/potion/PotionEffectType.java#L257
