### ISSUE TITLE
Breaking bottom block of Cactus doesn't break the plant.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#297]
Hi!
As i stated in the long list and in the title:
Breaking bottom of Cactus doesn't break the entire plant. It just floats.

**Comment by Wild1145** [comment]
This should be a fix of #249

**Comment by KakusiUgbe** [comment]
Thank you :)

**Comment by SpaceManiac** [comment]
See also #40.

**Comment by turt2live** [comment]
(Forwarding all physics tickets to #40)
