### ISSUE TITLE
No GUI for Enchanting table.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#299]
Hi!
Enchanting table acting like normal blocks. They can be placed on one another and no GUI opens up on right click.

**Comment by Wild1145** [comment]
Sounds like it links to #202

**Comment by Wild1145** [comment]
Also See #1

**Comment by KakusiUgbe** [comment]
Thanks :)

**Comment by turt2live** [comment]
Linking to #1

(Forwarding all inventory GUI tickets to #1)
