### ISSUE TITLE
Avils, placement and no GUI

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#301]
Hi!
Anvils when placed alwas snap to face East-West direction except for Slightly Damaged Anvil that snaps to North-South direction. Also there is no GUI for them.

**Comment by Wild1145** [comment]
See #1

**Comment by KakusiUgbe** [comment]
Thanks :)

**Comment by SpaceManiac** [comment]
Regarding placement, see #119.

**Comment by turt2live** [comment]
Linking to #1 and #119 (see above)

(Forwarding all inventory GUI tickets to #1)
