### ISSUE TITLE
Flower placed into Flowerpots.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#303]
Hi!
Flowers placed into flowerpots will be placed inside, but a 'duplicate' of the flower will be placed next to or above the flowerpot as well, unless the block next to or above is blocked. (players standing next to or on the flowerpot can block it from placing the extra flower.)

**Comment by Aaron1011** [comment]
This depends on PR https://github.com/GlowstoneMC/Glowstone/pull/267, which adds the necessary pack (Update Block Entity), which is repsonsible for setting the item in the flowerpot.

**Comment by Aaron1011** [comment]
@kdthehun: To clarify, the placing is currently purely client-side. The flower in the flowerpot isn't visible to anyone other than the placer, and will disappear for the placer on relog.

**Comment by turt2live** [comment]
Added flower pots to #325
