### ISSUE TITLE
Heads, player heads, skulls.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#304]
Hi!
Placing various type of heads displays proper texture in inventory, but goes back to default skeleton texture once placed. The Meta Data that it will have will only change it's orientation instead of texture. The collision box however will be where i placed the head even if the head is located elsewhere within that block's area.

**Comment by Wild1145** [comment]
Checkout #267

**Comment by KakusiUgbe** [comment]
Thanks :)

**Comment by turt2live** [comment]
Please see #119 (placement)
