### ISSUE TITLE
Armor stands can't be placed.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#305]
Hi!
Armor stands can't be placed in the world. I can take it into my hand but unable to place it.

**Comment by turt2live** [comment]
Created a parent ticket for similar issues related to interaction of blocks: #325

**Comment by turt2live** [comment]
Meant to link to #119

**Comment by ZephireNZ** [comment]
Armor stands are not blocks, the item is more like a 'special' spawn egg in reality.

**Comment by turt2live** [comment]
It becomes a block, just like doors, flower pots, skulls, and beds.

**Comment by ZephireNZ** [comment]
Armor stands are not blocks or blocks with tile entities, they are purely entities.

**Comment by turt2live** [comment]
Then it's #139 or #131 (in a VERY loose manner)

**Comment by ZephireNZ** [comment]
Yes, #139 looks like it would be the best one to put it in.

**Comment by turt2live** [comment]
Either way, this is a duplicate of SOMETHING :P

Technically it's related to all 3 previously mentioned tickets, #139 is just the "best fit" for now.

**Comment by KakusiUgbe** [comment]
Yes #139 is the best fit. Armor stands are almost like mobs in some sense. Water can push them without breaking them, they can fall as well. (As a test/fun sorta way we made like an armor display show with Armor stands in a vanilla server. Placed them in a looping water 'conveyor belt' and dressed them up each differently it looked cool )
