### ISSUE TITLE
Banners can't be placed.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#306]
Hi!
Unable to place Banners in the world. I can take into my hand, but not place it.

**Comment by turt2live** [comment]
Created a parent ticket for similar issues related to interaction of blocks: #325

**Comment by ZephireNZ** [comment]
I'm currently implementing Banners for both Glowkit and Glowstone :)

**Comment by turt2live** [comment]
Meant to link to #119
