### ISSUE TITLE
Note blocks can be placed, but do not emit sound.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#307]
Hi!
Note blocks can be placed, upon clicking it and right clicking it i can see the visualization of the notes coming from it as it's cycling through the notes/colors, but it doesn't emit any sound.

**Comment by Wild1145** [comment]
Might be linked to #242

**Comment by KakusiUgbe** [comment]
Thank you :)

**Comment by JeromSar** [comment]
This is fixed in https://github.com/GlowstoneMC/Glowstone/pull/277

**Comment by turt2live** [comment]
Linking into #325 and #116 instead of leaving this open. Thanks for the report though!

**Comment by dequis** [comment]
Also the relevant PR is #444 now
