### ISSUE TITLE
Beacon missing GUI.

### ISSUE THREAD

**Issue by KakusiUgbe** [GlowstoneMC/Glowstone-Legacy#308]
Hi!
Beacons when placed on Iron, Diamond, Gold blocks [3x3 or pyramid] it activates, the light beam comes out of it, and it can be colored by the use of stained glass, but when right clicked no GUI comes up on screen.

**Comment by Wild1145** [comment]
Same as #301 . It looks to be linked to #1

**Comment by KakusiUgbe** [comment]
Thanks :)

**Comment by turt2live** [comment]
Linking to #1

(Forwarding all inventory GUI tickets to #1)
