### ISSUE TITLE
Weird World Generation!

### ISSUE THREAD

**Issue by MCFilmMaker13** [GlowstoneMC/Glowstone-Legacy#309]
Hello, i'm not sure if this is supposed to happen, but when i start my glowstone test server using Build #66, the generated world looks kinda messed up. Any help on this would be greatly appreciated.
![2014-09-18_16 28 26](https://cloud.githubusercontent.com/assets/8825107/4326767/9eeb545c-3f72-11e4-8a5c-f1ee4c22e94a.png)
![2014-09-18_16 28 33](https://cloud.githubusercontent.com/assets/8825107/4326769/a894a102-3f72-11e4-949a-2b1f18ebfc25.png)

-MCFilmMaker13

**Comment by Tonodus** [comment]
Glowstone is a totally written from scratch and therefor not finished. Your world generation is "normal" for Glowstone at the current moment.

**Comment by turt2live** [comment]
https://github.com/GlowstoneMC/Glowstone/issues/76
