### ISSUE TITLE
Stop command sometimes doesn't stop the server

### ISSUE THREAD

**Issue by zml2008** [GlowstoneMC/Glowstone-Legacy#31]
The server does stop properly with a ctrl+c though, and plugins appear to be disabled when using the stop command.

**Comment by SpaceManiac** [comment]
I've noticed this before with certain plugins. Can I get a list? (`/plugins`)

**Comment by zml2008** [comment]
Plugins: PermissionsEx, CommandBook, TripCraft, WorldEdit
The issue appears to disappear when removing PermissionsEx tho

**Comment by SpaceManiac** [comment]
I'll see if PermissionsEx is doing anything particularly tricky with
threads.

---

From: "zml2008" 
reply@reply.github.com
Sent: Saturday, 06 August, 2011 1:58 AM
To: tad.hardesty@suddenlink.net
Subject: Re: [Glowstone] Stop command sometimes doesn't stop the server 
(#31)

> Plugins: PermissionsEx, CommandBook, TripCraft, WorldEdit
> The issue appears to disappear when removing PermissionsEx tho
> 
> On Fri, Aug 5, 2011 at 11:57 PM, SpaceManiac <

**Comment by zml2008** [comment]
Yeah, any plugin that has a thread leak prevents Glowstone from stopping. I've fixed it by changing the server shutdown command to System.exit(0);, but that messes with the storage queue.
