### ISSUE TITLE
Players can not pick up items

### ISSUE THREAD

**Issue by quickmind2020** [GlowstoneMC/Glowstone-Legacy#312]
When ever some tries to pick up any think they can't. Also when someone tries to drop something using q they can't. Also moving items into inventories don't work ether

**Comment by ZephireNZ** [comment]
Glowstone is still in development: a lot of stuff has yet to be done.

**Comment by ZephireNZ** [comment]
Related issue #4

**Comment by dequis** [comment]
I'd say it's a duplicate of that ticket

**Comment by turt2live** [comment]
Closed. See #4
