### ISSUE TITLE
Books can be written, but cannot be read

### ISSUE THREAD

**Issue by choyiny** [GlowstoneMC/Glowstone-Legacy#313]
Books can be written (The GUI pops up), but right clicking a written book does not open the GUI to read.

EDIT: Only happens if I sign the book.

**Comment by Aaron1011** [comment]
I believe this only applies to unsigned Book and Quills. I'm able to re-open and write before ther book is sign, but I can't open it after I sign it.

**Comment by choyiny** [comment]
It only applies to SIGNED book and quills. Sorry - Updated the description. Thanks.

**Comment by turt2live** [comment]
Added to #325 - closing. Thanks!
