### ISSUE TITLE
Add 1.8 crafting/smelting recipes

### ISSUE THREAD

**Issue by ZephireNZ** [GlowstoneMC/Glowstone-Legacy#314]
I've compiled a list of recipes added in 1.8 that will need to be added to the recipes.yml file:
- [x] Raw and Polished Diorite, Andesite and Granite
- [x] Coarse Dirt
- [x] Red Sandstone, its variants, and slabs/stairs
- [x] Prismarine
- [x] Prismarine Bricks
- [x] Dark Prismarine
- [x] Sea Lantern
- [x] Slime Block - both ways
- [x] All new types of wooden fences, gates, doors
- [x] Iron Trapdoor
- [ ] Banners (could be tricky, uses NBT)
- [x] Armor Stand
- [x] Leather from Rabbit Hide
- [x] Cooked Rabbit
- [x] Rabbit Stew
- [x] Chiseled Stone Bricks
- [x] Cracked Stone Bricks
- [x] Mossy Stone Bricks
- [x] Mossy Cobblestone

This relates to the one item on #131. Please tell me if I've missed anything :)

**Comment by dequis** [comment]
A bit unrelated, but do we even have a way to craft most of these right now? Other than the 2x2 grid in the inventory.

**Comment by Wild1145** [comment]
I thought the crafting table GUI was built?

**Comment by dequis** [comment]
Eh, well, there's #202 so the GUI part of it is broken right now. #237 should have a fix for it but the author is MIA. Just wondering if there's some other way I'm missing, because without this it's kinda hard to test recipes.

**Comment by Wild1145** [comment]
Ahh, Didnt see #202 I had read the one about the initial adding of the GUI, just not that it had broke. As for testing... Short of modded clients and such I dont think its possible really without a working GUI for the workbench.

**Comment by dequis** [comment]
Could close this one and replace it with #438

**Comment by turt2live** [comment]
Closing as #438 is more detailed for the remainder of this issue
