### ISSUE TITLE
Trapped chest does not open

### ISSUE THREAD

**Issue by choyiny** [GlowstoneMC/Glowstone-Legacy#316]
Trapped chest does not open the GUI like normal chests do.

**Comment by Wild1145** [comment]
I think this is the same in Vanilla, though I might be mistaken. I dont remember them opening in Craftbukkit either...

**Comment by dequis** [comment]
Just tested with spigot and it works just like a normal chest

**Comment by Wild1145** [comment]
Hmm, maybe its something else im thinking about then, just ignore my first comment.

**Comment by turt2live** [comment]
Is it that right clicking does nothing or is the wrong GUI shown?

**Comment by dequis** [comment]
If you have a block in hand, it gets placed. Otherwise nothing

**Comment by turt2live** [comment]
Linking to #325 (as with every other interaction ticket).
