### ISSUE TITLE
Shift-clicking in inventories does not work

### ISSUE THREAD

**Issue by choyiny** [GlowstoneMC/Glowstone-Legacy#317]
Shift clicking to chests, droppers, hoppers and dispensers do not work. Same with shift clicking out.

**Comment by dequis** [comment]
Works for me. More detailed instructions on how to reproduce would be appreciated

**Comment by Wild1145** [comment]
If you dont include how to reproduce the issue, its near impossible for the developers to figure out the issue you are having and find a fix for it!

**Comment by choyiny** [comment]
i will do more testing. It just happened without me doing anything special...

EDIT: Nevermind... It is because I shift clicked and it didn't put it in the chest.

**Comment by turt2live** [comment]
Duplicate of #1
