### ISSUE TITLE
Water won't flow, nor will mobs spawn.

### ISSUE THREAD

**Issue by tsdev22** [GlowstoneMC/Glowstone-Legacy#321]
If I were to spawn a mob with a spawn egg, nothing will happen.  Also, when I do /spawnmob [mob] it says "Not supported yet."

**Comment by dequis** [comment]
Huh i'm surprised we don't have a ticket for water.

Also, one ticket per issue, please! Make another ticket for one of those two and edit this one

**Comment by turt2live** [comment]
#40 and #139 respectfully. 

(Forwarding all physics tickets to #40)

**Comment by dequis** [comment]
*respectively

**Comment by turt2live** [comment]
*english is not my strong point
