### ISSUE TITLE
HTML5 site issues

### ISSUE THREAD

**Issue by Bertware** [GlowstoneMC/Glowstone-Legacy#322]
In order to be HTML5 compliant, there are 2 minor issues that need to be resolved on glowstone.net:
The following files in gh-pages should be altered:
### in index.html:

> `<img src="img/block.png">` should have an alt attribute on the homepage.
> Suggested fix: `<img alt="logo" src="img/block.png">`
### in _includes/footer.html:

> `<script>` element should be inside the `<body>` tag
> 
> ```
> </body>
>    <script>
>        $(function() {
>            $("[rel=tooltip-top]").tooltip({placement: "top"});
>        });
>    </script>
> ```
> 
> to  
> 
> ```
> <script>
>        $(function() {
>            $("[rel=tooltip-top]").tooltip({placement: "top"});
>        });
>    </script>
>    </body>
> ```

**Comment by Tonodus** [comment]
Why don't you open a PR if you have already fix the issue?

**Comment by Bertware** [comment]
Issues with creating a PR to the gh-pages branch, permission denied.

**Comment by dequis** [comment]
Went ahead and did it for you

**Comment by Wild1145** [comment]
There shouldn't be any permissions issues on different branches... Probably something for  @SpaceManiac to check into.

**Comment by dequis** [comment]
It worked for me so i'm blaming @Bertware. Not a big deal, though.

**Comment by Wild1145** [comment]
Might have been the way github likes to mess around when switching between projects and branches, It has given me the run around more than once ;)
