### ISSUE TITLE
Interaction not complete

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#325]
Right clicking certain blocks do not work in expected ways. This includes things like doors opening, starting fire, etc. A more complete list of issues will be added over time (for now, see the soon to be linked PRs that will make this a parent). 

Known Cases (check = fixed in master):
- [x] Fence gates
- [x] End portal frames / Eye of Ender
- [x] Trap doors
- [ ] Jukebox with disks
- [ ] Noteblocks
- [ ] Bonemeal on plants
- [x] Doors
- [ ] Pressure plates
- [ ] Trapped chest
- [x] Buckets
- [x] Signed books cannot be read
- [ ] Flower pots
- [ ] more?

Edit: Marked as "bug" and "feature" because some are just broken, others are just not implemented.

**Comment by Aaron1011** [comment]
I'm working on Jukeboxes.

**Comment by gdude2002** [comment]
Bonemeal on plants: https://github.com/GlowstoneMC/Glowstone/pull/374

**Comment by jaredStef** [comment]
I'm working on trapped chest.

**Comment by turt2live** [comment]
Trapped chests are dealt with in another PR, #358

**Comment by turt2live** [comment]
Jukeboxes and note blocks: #444

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
