### ISSUE TITLE
BlockPlacementHandler ignores Flint&Steel clicking TNT

### ISSUE THREAD

**Issue by Tonodus** [GlowstoneMC/Glowstone-Legacy#330]
It seems like this line causes problems:
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/net/handler/play/player/BlockPlacementHandler.java#L81

It compares the ItemStack the player has currently in hand (on the server side) and the information from the packet send from the player. If they don't match the server just does nothing.

From my testing it seems that the client increase the damage of the Flint&Steel-ItemStack when right-clicking TNT before the packet is send. Therefor the server's ItemStack has a damage of 0 (f.e.), while the packet's ItemStack has a damage of 1. Then they aren't equal and the server stops executing the event.

I would just remove this check, relating to wiki.vg:
"[...] with the implementation of server-side inventory, a Notchian server seems to ignore the item ID, instead operating on server-side inventory information and holding selection".

To test this issue do the following:
Open the file mentioned above in your IDE and set a breakpoint on the mentioned line.
Go into creative mode, give yourself TNT and Flint&Steel.
Go into survival mode.
Place the TNT somewhere and rightclick it with Flint&Steel.
Open your debugger and check the values from holding and message.getHeldItem() => they differ in the damage/durability value.

**Comment by turt2live** [comment]
This is no longer valid due to somewhat recent commits on master relating to explosions. If I'm wrong, please comment back as soon as possible with detailed information regarding how wrong I am. Thanks!

**Comment by Tonodus** [comment]
@turt2live 
All commits handling TNT were contributed by me, without resolving this issue (see https://github.com/GlowstoneMC/Glowstone/pull/284#issuecomment-62254043 and https://github.com/GlowstoneMC/Glowstone/pull/284#issuecomment-62264339).
In fact, this issue is still as valid as it was when I opened it.

**Comment by turt2live** [comment]
As stated, detailed information then? I spent about an hour testing this with no issues.

**Comment by Tonodus** [comment]
@turt2live Well, have you tried igniting TNT by right-clicking it with flint and steel in survival mode? On a clean, uppdated master the TNT disappears for me without any explosion. This is caused by this bug: Glowstone ignores the right-click action (as stated earlier), so no explosion occurs. The disappeared TNT is just a client glitch, it's still there on server side.
