### ISSUE TITLE
Add Spigot API to Glowkit?

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone-Legacy#335]
I was wondering if we could add the extra events Spigot API adds to the Glowstone API:
https://github.com/SpigotMC/Spigot-API/tree/master/src/main/java/org/spigotmc

Also, should/can we merge Spigot changes to the Bukkit API (https://github.com/SpigotMC/Spigot-API/tree/master/src/main/java/org/bukkit) with Glowkit?

**Comment by ZephireNZ** [comment]
This would more likely be a thing to add to Glowkit, rather than Glowstone. I'll create a Issue there with more info :)

**Comment by ZephireNZ** [comment]
Created an issue at GlowstoneMC/Glowkit#18

**Comment by mastercoms** [comment]
Closing because of the new issue at Glowkit.
