### ISSUE TITLE
How to use the console?

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#338]
How to use the console?
Is that the console can not write anything, I guess it will be a bug...

**Comment by ZephireNZ** [comment]
Er... what do you mean? If you're just running the jar file on your PC, you need to run it from 'cmd.exe' to be able to see the console output. It should act the same as CraftBukkit's console.

**Comment by Krowerom** [comment]
I'm trying this out for the first time on Mac OSX, the start command file recommended on the wiki throws up the following error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/glow stone/GlowServer : Unsupported major.minor version 51.0
If I just run the glowstone.jar, nothing appears on my screen, but opening minecraft, I see the server is running.
As with this issue, I cannot see console, nor even the process running on my iMac, so can only 'stop' the server by powering down my computer.

**Comment by dequis** [comment]
> Unsupported major.minor version 51.0

@Krowerom That error means you need to upgrade to java 7. What commandline are you using? Just `java -jar glowstone.jar` should work

@MagicXinventor is your issue the same, or something else?

**Comment by ZephireNZ** [comment]
Ah, I believe Macs ship with Java 6 by default. Can you run "java -version" just to be sure?

**Comment by Krowerom** [comment]
I am running the latest Java (Version 7, update 67), it was the first thing I checked - I checked this on my Java control panel... if I run java -version in the terminal, it shows I'm still on 1.6... I'll work on fixing that and hopefully will be able to report back that it is all working...
The command line is as it shows in the Wiki, and yes, I did the chmod A+X too:
#!/bin/bash
cd "$( dirname "$0" )"
java -Xmx1024M -jar glowstone.jar -o true

**Comment by Krowerom** [comment]
I had updated to Java 7 a long while back.. BUT Oracle doesn't automatically update the java version used in Terminal on macs (it was still on 6).. I found a very useful page taking me through the process.. 
https://gist.github.com/johan/10590467
Now it runs fine.  Thanks gents!

**Comment by ZephireNZ** [comment]
No problem. Can you close this issue then? (Should be a button down the bottom)

**Comment by Krowerom** [comment]
It solved my issue.. But was I having the same issue as MagicXinventor? He opened the issue, I kinda just hijacked it. If Magic is happy to close it, then that's good with me :)

**Comment by ZephireNZ** [comment]
Oh, derp. Didn't even realise you weren't him. My bad haha
