### ISSUE TITLE
Custom API?

### ISSUE THREAD

**Issue by nikosgram** [GlowstoneMC/Glowstone-Legacy#339]
Why you don't make your API? I can help you about the Glowstone API.
I have started already a Project for the Glowstone.
It looks like the Bukkit API but it is a lot easy from this. :smiley_cat:

**Comment by ZephireNZ** [comment]
We've currently got Glowkit, which is based on Bukkit, that we're using currently. That will allow us to add to the Bukkit API as we wish, including changes to 1.8 and such. It's also backwards compatible, which is very nice.

There has also been talk of supporting the Sponge API. The API is still heavily under development, but it's being made in a way that should be supportable in Glowstone.

**Comment by nikosgram** [comment]
Ow, thats cool :smile: :+1:
If you have a plan then ok. :sweat_smile:

**Comment by nikosgram** [comment]
Why you don't share the Glowkit?

**Comment by Postremus** [comment]
https://github.com/GlowstoneMC/Glowkit <- Glowkit

2014-09-23 15:17 GMT+02:00 Nikos Grammatikos notifications@github.com:

**Comment by nikosgram** [comment]
Thanks @Postremus. :smile:
