### ISSUE TITLE
SportBukkit modifications

### ISSUE THREAD

**Issue by parkervcp** [GlowstoneMC/Glowstone-Legacy#347]
Add in SportBukkit modifications from such things like TNT balancing and other stuff.

https://github.com/OvercastNetwork/SportBukkit

**Comment by turt2live** [comment]
Please consider opening a PR for your desired changes :)

**Comment by turt2live** [comment]
Closing because the SportBukkit changes are more strongly tied to the API side with the implementation being a side effect. See GlowstoneMC/Glowkit#21
