### ISSUE TITLE
Redstone Torch Effect Failed.

### ISSUE THREAD

**Issue by nikosgram** [GlowstoneMC/Glowstone-Legacy#348]
![Example1](http://i.imgur.com/1agP0mO.png)
![Example2](http://i.imgur.com/XlgtRnU.png)

**Comment by ZephireNZ** [comment]
Redstone is not yet implemented in Glowstone. As such, torches won't power redstone, repeaters won't light up, etc.

**Comment by SpaceManiac** [comment]
Linking #116.
