### ISSUE TITLE
Sword prevents dig even in survival

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#349]
The sword dig checks in `DiggingHandler` need to be changed to operate only in creative mode.

**Comment by mastercoms** [comment]
https://github.com/GlowstoneMC/Glowstone/blob/2ea5576273e89106a2e22ce3ba90c9ce8fc21e31/src/main/java/net/glowstone/net/handler/play/player/DiggingHandler.java#L52
needs to be changed to
if (player.getGameMode() == GameMode.CREATIVE && holding != null && EnchantmentTarget.WEAPON.includes(holding.getType())) {

**Comment by ZephireNZ** [comment]
Fix on PR #356
