### ISSUE TITLE
cmd: ready to connect, or, failed to bind to address maybe it is already in use?

### ISSUE THREAD

**Issue by EpicSharkNoob** [GlowstoneMC/Glowstone-Legacy#350]
Hi Everyone,

My name is EpicSharkNoob, and I am here to answer a question that some of you may have.  That question is, "What do I do if my glowstone server says 'failed to bind to address, maybe it is already in use?'".  Well, if that happens, all you have to do is:
Windows 8:  Press Ctrl-Alt-Delete, then click task manager, then click the drop-down arrow that says 'more details', then scroll down to where it says, under background processes, Java, then click 'end task'.  Then close task manager and run your server.  If it says, 'ready to connect' or 'ready for connections', then that means it's done.  If you open Minecraft (with the CMD run console open, of course), and then clikc on multiplayer, you should see that your server is up and running!

Thanks for reading this important message,

```
                                                                         Chris A. :)
```

**Comment by Wild1145** [comment]
You have opened this as a issue (Of which it isnt), this sort of thing would probably be better located in our Wiki, as thats probably where people will look for these sorts of things!

**Comment by SpaceManiac** [comment]
Closed since it isn't really an issue. Decent guide though, feel free to add to the [wiki](https://github.com/GlowstoneMC/Glowstone/wiki)!
