### ISSUE TITLE
MySQL Driver

### ISSUE THREAD

**Issue by ferdl9999** [GlowstoneMC/Glowstone-Legacy#354]
Hi,

i get this error on startup for plugins that uses mysql: 2014/09/27 16:12:25 [WARNUNG] java.sql.SQLException: Driver class was not found for MySQL database.  Missing jar with class com.mysql.jdbc.Driver.

**Comment by SpaceManiac** [comment]
See #143 and the [Library Management](https://github.com/GlowstoneMC/Glowstone/wiki/Library-Management) wiki page.

**Comment by Tonodus** [comment]
This should solve your problem: https://github.com/GlowstoneMC/Glowstone/wiki/Library-Management

**Comment by ferdl9999** [comment]
Thanks a lot!
But now im getting this message on startup:
16:58:20 [INFORMATION] Binding to address: /37.187.xxx.xx:25565...
16:58:20 [INFORMATION] [NoCheatPlus] Post-enable running...
16:58:20 [SCHWERWIEGEND] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already in use?
        at net.glowstone.GlowServer.bind(GlowServer.java:415)
        at net.glowstone.GlowServer.main(GlowServer.java:91)

The ip is the same, but the port isn't the same as in the config (config/glowstone.yml).
I run more than one servers on this machine, port 25565 is already in use. This server should use port 25591, but it won't.

**Comment by ZephireNZ** [comment]
That almost always means that you have a server already running. Kill the server (eg with task manager), or simply restart, and then try again.

**Comment by ferdl9999** [comment]
But i set the port in the glowstone.yml to another one as shown up.....
The port that is shown up is already in use. The another port not.

**Comment by SpaceManiac** [comment]
Could you pastebin or paste here or on gist the contents of your `glowstone.yml` file? This functionality is supposed to work and I haven't figured out why some people keep reporting it doesn't.

**Comment by ferdl9999** [comment]
http://pastebin.com/LhqZCQtx

**Comment by Tonodus** [comment]
@ferdl9999: Try removing the ' before and after the port number.

**Comment by ferdl9999** [comment]
Thanks, it works!

Could you please add support for Minecraft 1.7 + 1.8? This would be very nice

**Comment by ZephireNZ** [comment]
Currently we half-support 1.8 - all the items are there, they just aren't all implemented in the world.

As for 1.7 support, we won't be supporting it. You cannot have two client versions connect at the same time and have everything work properly, it's easier just to support the most recent release and stick to that.

**Comment by ferdl9999** [comment]
Couldn't you support both versions? Makes it like in spigot, 1.8 items aren't supported, but you can join with 1.8 client. The most of the players haven't updated to 1.8

**Comment by dequis** [comment]
It's technically possible, just won't happen unless someone goes ahead and does all the work required to have both versions working without client crashes.

You could try putting bungeecord in front of glowstone.

**Comment by ferdl9999** [comment]
I have BungeeCord in front of glowstone, but if i want to connect to the server, i get the message "Outdated client"

**Comment by Tonodus** [comment]
You probably must use two profiles (one for 1.7 and 1.8) in your MC launcher to connect to Glowstone/other 1.7 servers, because IMO Glowstone won't support 1.7 anymore.

**Comment by SpaceManiac** [comment]
Glowstone does not currently plan multi-protocol support. The preference is to stably implement one version at a time.

**Comment by Squawkers13** [comment]
The library management fails (Cannot find net.glowstone.GlowServer?) on Build 78
Using a .jar in folder

**Comment by dequis** [comment]
So replace the `glowstone.jar` part of the commandline with the right path to the jar file. Also remember to `cd` to the right directory before running it.

For example:

```
/path/to/server/glowstone.jar
/path/to/server/libraries/sqlite-jdbc-3.7.2.jar
/path/to/server/world
/path/to/server/[other files here]
```

In this case you'd run:

```
cd /path/to/server/
java -cp glowstone.jar:libraries/sqlite-jdbc-3.7.2.jar net.glowstone.GlowServer
```

Note the `libraries/` part before the sqlite-jdbc filename.

**Comment by Squawkers13** [comment]
The code is in a .bat file in the same directory as the glowstone.jar and the sqlite-jdbc-3.7.2.jar.

**Comment by SpaceManiac** [comment]
Try using `;` instead of `:` between the two jars.

**Comment by Squawkers13** [comment]
That worked :)
