### ISSUE TITLE
Commands?

### ISSUE THREAD

**Issue by EpicSharkNoob** [GlowstoneMC/Glowstone-Legacy#355]
Hi,

A few of you may already know me, but for those of you who don't, my name is EpicSharkNoob.  I am typing this today to ask a question in which I do not have the answer for.  When I go on my server, after I op myself, I type "/gamemode 1" to switch into Creative mode.  However, it says "you are not allowed to use this command".  Also, when I post a grassland world on my server to play on, the grass in the grassland is a dark, pale green color, instead of the usual lime green color that grassland grass is supposed to be.  Can anyone help me with these questions?

Thanks,
                          EpicSharkNoob

**Comment by Lemonbus** [comment]
About the grass, I do believe the only biome that the server is in is "ocean". That being said, color of grass change in each biome.

**Comment by mastercoms** [comment]
I believe opping is case sensitive.

**Comment by daboross** [comment]
For the first question:

Were you online when you used `/op` in the console?

If you weren't online when you used `/op`, it will have opped the wrong UUID, thus not actually giving you OP. See https://github.com/GlowstoneMC/Glowstone/issues/227.

For the second question:

World generation currently is more simple than Minecraft's, and it does not generate different biomes. If you import a world from a minecraft server, it will show, but Glowstone currently does not generate biomes.

**Comment by EpicSharkNoob** [comment]
Thank you for all of your answers.  However, I have a question about what
Googlelover1234 said.  How do you change the biome from ocean to all
biomes?  Also, in response to Dabo Ross' answer, yes, I was online when I
opped myself.  I opped myself not only in the console (cmd), but in-game
too.

Thanks,
                          EpicSharkNoob

**Comment by SpaceManiac** [comment]
> How do you change the biome from ocean to all biomes?

You'd have to use a world generator that supports biomes, either a custom one or wait until we get our world generator using them (see #76).

**Comment by EpicSharkNoob** [comment]
Thank you for your response.  I will try that now.

EpicSharkNoob

**Comment by EpicSharkNoob** [comment]
By the way, do you know when you will release a world generation api for
glowstone?

Thanks,

EpicSharkNoob

**Comment by EpicSharkNoob** [comment]
Sorry for all the separate emails,

do you also know of a link to a basic world generator plugin?  If so,
please paste it in an email.

Thanks,

EpicSharkNoob

**Comment by daboross** [comment]
> By the way, do you know when you will release a world generation api for
> glowstone?

Glowstone implements Bukkit's world generator API afaik.

> Sorry for all the separate emails,
> 
> do you also know of a link to a basic world generator plugin?  If so, please paste it in an email.
> 
> Thanks,
> 
> EpicSharkNoob

Check out http://forums.bukkit.org/threads/chunkgenerators-blockpopulators-faq.22795/.

For the OP, I'm not sure why it wouldn't work if you used your exact name with same capitalization and when you were online. Could you pastebin your ops.json?

**Comment by EpicSharkNoob** [comment]
Thank you so much.  I will check the link right now.  Hopefully no more
errors or issues on my part will come up.

Thanks again,

EpicSharkNoob
