### ISSUE TITLE
Personal Skins not Rendering

### ISSUE THREAD

**Issue by Varlanou** [GlowstoneMC/Glowstone-Legacy#359]
It seems that I can only see the basic 'steve' skin. I tried the reupload my skin as both a pre 1.8 version and a 1.8 version. Both ways the server continues to pull the 'steve' texture I have in my texture pack. I also tried removing the 'steve' from my texture pack and even disabling the pack altogether. Each time my character renders with only the basic 'steve' skin. I have not yet added any plugins to the server. I am however using a world map I created in WorldPainter. Though that shouldn't affect how the server handles personal skins. It's almost as if the server refuses to connect to minecraft.net to pull the skin.

**Comment by dequis** [comment]
...closed for what reason?

**Comment by Varlanou** [comment]
Sorry for the way late reply. If I remember correctly I closed this due to glowstone not being fully created and lacking certain features, such as person user skins.

**Comment by gdude2002** [comment]
Sure, but if there wasn't a ticket for it, it can only help to have one.

Did you have any more detail on this? Any exceptions, anything like that? Does [Glowstone++](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus) have the same problem?
