### ISSUE TITLE
[meta] Questions?

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#362]
A few users seem to be using github issues for general questions, not necessarily bugs.

For some projects, this is perfectly acceptable, and is handled by labeling the github issue as "question". Those projects encourage users to submit any support questions through the tracker.

For other projects, the tracker is strictly only for bugs, and vague questions submitted as issues get closed right away, often redirecting users to a forum or mailing list. Which we don't have.

Sooo... where do we stand on this? Are 'question' tickets acceptable here, or do we want something else?

**Comment by daboross** [comment]
I think most of the projects that don't allow this also have some other method of communication though, like a forums.

**Comment by Tonodus** [comment]
Until we have some other sort of communication, we have to accept user open issues for general questions IMHO.

Well, they might use IRC, but not everytime someone is online, not everytime the online person can actually help. So we're in need of a system like a forum, where you can sign off, the question get answered and you sign in again.
Maybe we can redirect people to Bukkit Forums (since they have a "Bukkit alternatives" there), but I'm certain that this wouldn't the optimal way.

**Comment by SpaceManiac** [comment]
As a temporary measure, I will start using a "Support" label for support tickets here. When forums are set up we can point support questions there.

**Comment by mastercoms** [comment]
Maybe we can have a subreddit?

**Comment by PaulBGD** [comment]
We have a subreddit.

**Comment by mastercoms** [comment]
So we can use it for support

**Comment by PaulBGD** [comment]
Sure, go ahead. I'm subscribed, and would love to help answer some of your questions.

**Comment by gdude2002** [comment]
There's `/r/glowstone` (which is about us) but we don't actually have moderation/admin access to it. I think @SpaceManiac is working on that.

@PaulBGD is that what you were thinking of? Or is there another?

**Comment by PaulBGD** [comment]
@gdude2002 Yeah, the reddit.

**Comment by dequis** [comment]
This ticket was supposed to be about the forum originally, but all the discussion is happening in #170 instead. Closing this one as a duplicate of that one. Also some repo admin should remove the milestone from this, so that it doesn't get marked as progress

**Comment by PaulBGD** [comment]
Although closed, would like to mention that the official forums are up.
https://forums.glowstone.net/
