### ISSUE TITLE
Glowstone Sever Not Working With The Run.bat 

### ISSUE THREAD

**Issue by XxkingassassinxX** [GlowstoneMC/Glowstone-Legacy#363]
It Does The Thing The Picture Is In The Attached File! Pleaes Help
i am Sooo Desprate For A 1.8 Server 
Thanks,
XxkingassassinxX

**Comment by bendem** [comment]
The attached file:
![](http://i40.photobucket.com/albums/e233/obsidiantnt/Untitled_zps5ebefe3a.png~original)

Relevant code:
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/ConsoleManager.java#L61

**Comment by XxkingassassinxX** [comment]
Oh i fixed It By Renaming The File With My Server Glowstone.jar and run bat to Glowstone

**Comment by daboross** [comment]
This was fixed by renaming the directory `Glowstone Server!` to just `Glowstone`.

It seems that this problem occurs with directories with spaces in them.

**Comment by ZephireNZ** [comment]
It's not spaces. Exclamation points are interpreted as zip files in Java. It thoroughly confuses the server.

**Comment by Tonodus** [comment]
@XxkingassassinxX could you please close this as it is solved?
