### ISSUE TITLE
Custom generators fail if trying to use `World.getBiome(int, int)` while generating.

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone-Legacy#364]
Custom generators fail if trying to use `World.getBiome(int, int)` while generating.

Error:

```
java.lang.ArrayIndexOutOfBoundsException: -1
         at net.glowstone.constants.GlowBiome.getBiome(GlowBiome.java:36)
```

https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/GlowChunk.java#L567 returns -1 when chunk isn't initialized.

Then https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/GlowWorld.java#L1065 calls GlowBiome.getBiome with -1.

https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/constants/GlowBiome.java#L35 throws ArrayIndexOutOfBoundsException when passed -1.

This causes `GlowWorld.getBiome(int x, int z)` to fail from inside chunk generators.

Perhaps a fix would be to have GlowChunk to return a default biome number instead of -1 when uninitialized?

**Comment by SpaceManiac** [comment]
This issue was noticed and fixed incidentally in 5d5412172302d8727f9c89fede9c670f17d42118. Now a BiomeGrid keeps its own buffer and sets the chunk's biomes after it's been initialized.
