### ISSUE TITLE
crafting table window  not correct

### ISSUE THREAD

**Issue by ikke18** [GlowstoneMC/Glowstone-Legacy#366]
the crafting tabble is not how it should be here is a image of it:
![crafting table](https://cloud.githubusercontent.com/assets/1534569/4435699/57b0e5e6-4753-11e4-8439-6e7182ce46e6.PNG)

**Comment by Tonodus** [comment]
Duplicate of #202 (which is closed for #1)

**Comment by SpaceManiac** [comment]
Thanks for the report, see also the issues linked above!
