### ISSUE TITLE
dubble door's not functioning

### ISSUE THREAD

**Issue by ikke18** [GlowstoneMC/Glowstone-Legacy#367]
dubble door's are realy hard to open (if it opens only 1 side opens) and you need to hit it 4 to 5 time to get it open.
![dubble door](https://cloud.githubusercontent.com/assets/1534569/4435704/a5664d30-4753-11e4-9869-b0a5b621c82e.PNG)

**Comment by ZephireNZ** [comment]
Well, first off, Iron doors aren't meant to be openable by hand(only wooden ones)...

Regardless, a lot of the game logic is still WIP, I'm not sure whether doors are fully implemented yet.

Relates to #325

**Comment by ikke18** [comment]
ok, thanks fot your response. 
1. the server is using lockette. (no error's at the plugin)
2. it was with all doors.

but as said in post #325 it is not working properly right now

**Comment by hihiuk123** [comment]
I can't seem to even place doors at all!

**Comment by Tonodus** [comment]
@hihiuk123 Glowstone is a WIP, doors aren't implemented yet.
