### ISSUE TITLE
Problematic Blocks and Items.

### ISSUE THREAD

**Issue by Varlanou** [GlowstoneMC/Glowstone-Legacy#369]
So there are a few things I am having issues with.
1. Can't seem to do anything with the beds. I mean I can right-click on them but it doesn't actually do anything.
2. The thin layer of snow block won't stack. When I try to place a thin snow on top of another thin snow it acts more like carpet and places it a block's height above the first piece.
3. I cannot seem to pick up items that have been dropped and the Q key is no longer allowing me to drop items. (I can still drop them by dropping them outside the inventory window, but cannot pick them up again after that.)
4. Falling blocks like Gravel aren't falling. They just float there.

Also as a point to note, I do not have any plugins added, and I have not changed any gamerules, code, settings, or anything in the server's 'config' folder.

**Comment by ZephireNZ** [comment]
1. A lot of block logic is not yet sorted out. Duplicate of #325 
2. Placing logic needs to be updated for snow layers. Duplicate of #119 (and #223)
3. Items are not fully implemented yet. Duplicate of #4 (and #312)
4. Gravity isn't merged in yet, but there's a PR open currently: #249

Unless you have anything else, this should be closed.
