### ISSUE TITLE
Friends can't join the server

### ISSUE THREAD

**Issue by Monster722846** [GlowstoneMC/Glowstone-Legacy#375]
My friends can't join ,but I have port forwarded and set online-mode to false (I have tried it with online mode on true) btw mt friends have cracked minecraft

**Comment by GermanCoding** [comment]
Can your friends ping the server (Can they see it in the server list)?

**Comment by hintss** [comment]
If you replace it with craftbukkit, can they join?

**Comment by turt2live** [comment]
Generally cracked or otherwise illegal clients are not supported. @SpaceManiac ?

**Comment by SpaceManiac** [comment]
I would prefer not to provide support to an admitted pirate.
