### ISSUE TITLE
World generation not using provided seed

### ISSUE THREAD

**Issue by TOLoneWolf** [GlowstoneMC/Glowstone-Legacy#376]
When adding the seed option to the glowstone.yml the server will not generate with the correct seed.
for example if you put "seed: 5555555" it generates with this seed: "1360978005" every time.

Also multiverse doesn't seem to use the seed given. It picks a random seed and edits the setting to match the world and not the other way around. I don't know if that is their error or if it is linked to this as well.

Or I could be a complete idiot and be missing a command/settting? if so sorry.

**Comment by ZephireNZ** [comment]
Are you meaning that only the seed "5555555" will always generate with "1360978005", or that every seed value generates with "1360978005"

**Comment by SpaceManiac** [comment]
In this case, `5555555` is being interpreted as a text seed and `1360978005` is its hash used as the actual seed. This is currently intended behavior. Do you definitely need `5555555` to be the actual numeric seed?

I can't say what's up with Multiverse, things should be working fine provided you're creating a brand-new world and not importing an existing world (in which case the imported seed is used). Maybe it's doing the same thing?

**Comment by TOLoneWolf** [comment]
why is it being interpreted as text? yes i want the number to be the number used! I want it to use the seed value i give it not make a new value from that value.
IDK why multiverse refuses to over ride the seed glowstone is trying to use when generating a new world.
