### ISSUE TITLE
Crafting grid 

### ISSUE THREAD

**Issue by RonaldPhilipsen** [GlowstoneMC/Glowstone-Legacy#382]
I've just started a Glowstone server with the latest build,
but the crafting grid is weird, its one line where you can put in stuff,
idk if this is intentional but i've added a screenshot

![untitled](https://cloud.githubusercontent.com/assets/8189044/4515505/fac32a66-4bc0-11e4-98e9-0dd44627943a.png)

**Comment by ZephireNZ** [comment]
Duplicate of #1 

Mind closing this issue?
