### ISSUE TITLE
Server Not Displaying Online

### ISSUE THREAD

**Issue by AJLedbetter123** [GlowstoneMC/Glowstone-Legacy#389]
Morning All,

I've installed the plugin after watching numerous videos on Youtube but I've had to do it a slightly different way as the serer isn't hosted by me. I'm using the Multicraft control panel to install.

I've posted the console messages that I have received which all seem normal but the server won't simply as online - ' Can't connect to server'

http://pastebin.com/aVGqJrwJ

Any ideas?

**Comment by SpaceManiac** [comment]
I understand this was handled on the IRC. Feel free to correct me if it wasn't.

**Comment by AJLedbetter123** [comment]
Yeah that issue was resolved but something else has cropped up, after copying my world over etc, everything is here but for some reason the banners or armor stand won't display,

Anything I can do?

**Comment by greatman** [comment]
Those are entities and it's still a work in progress.

**Comment by AJLedbetter123** [comment]
Thanks for the help - Lastly, after copying the world over, the chests seem to be empty now, any fix for this?

**Comment by AJLedbetter123** [comment]
It's the same for the animals we had at spawn, they're also all gone.

**Comment by jimmikaelkael** [comment]
There's a lot of work in progress.
Please wait before to put Glowstone in production.
