### ISSUE TITLE
glowstone.net does not work

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone-Legacy#394]
http://glowstone.net says there isn't a github page there, however, the site is accessible using https://glowstonemc.github.io/

**Comment by JeromSar** [comment]
Site works fine for me. Perhaps give it some time. Might be some DNS changes that need to propagate.

**Comment by olliestanley** [comment]
Works fine for me also.

**Comment by ZephireNZ** [comment]
Yep, fixed for me now as well. Looks like it DNS just needed to propagate.

**Comment by SpaceManiac** [comment]
It's not visible but there's still something weird going on, I'm working on it.

**Comment by mastercoms** [comment]
It works for me now.

**Comment by choyiny** [comment]
Works for me too.
