### ISSUE TITLE
IP Line not readily available

### ISSUE THREAD

**Issue by Lenovive** [GlowstoneMC/Glowstone-Legacy#395]
There is no line for IP in the glowstone.yml. If added in manually itr doesn't seem that the file can be saved.

**Comment by mastercoms** [comment]
Could you use pastebin or something to show your glowstone.yml file? Make sure you're using spaces, not tabs

**Comment by SpaceManiac** [comment]
You should simply be able to add the `ip:` line manually and have it work. There shouldn't be anything preventing you from saving your file. Maybe you're under Windows and the server was running and thus using it at the time, or some other file permissions error?

**Comment by turt2live** [comment]
May be due to the server seeing `server.properties` and converting it over and over. May want to consider adding some functionality to rename the `server.properties` after it's been converted.

**Comment by SpaceManiac** [comment]
The migration code is [only run when `glowstone.yml` doesn't already exist](https://github.com/GlowstoneMC/Glowstone/blob/b431f691f5e32562a6d0a2e3f1ea01be9111ccce/src/main/java/net/glowstone/util/ServerConfig.java#L168-168).

**Comment by turt2live** [comment]
That didn't work for me on a test run at one point O_o  I might have just broken something though

**Comment by gdude2002** [comment]
So, what's going on with this ticket? Did @Lenovive solve their problem?

**Comment by SpaceManiac** [comment]
Closing for now. If you still have problems comment again.
