### ISSUE TITLE
Water and Lava

### ISSUE THREAD

**Issue by EpicSharkNoob** [GlowstoneMC/Glowstone-Legacy#396]
How come I can't spawn water or lava when right-clicking with a water or lava bucket.  How come?

**Comment by turt2live** [comment]
Functionality is not fully implemented yet.

**Comment by EpicSharkNoob** [comment]
Do you know approximately when?

**Comment by PaulBGD** [comment]
Whenever it's implemented?

**Comment by turt2live** [comment]
Whenever https://github.com/GlowstoneMC/Glowstone/pull/236 or a similar PR is pulled

**Comment by turt2live** [comment]
Added buckets to #325. Please see that issue
