### ISSUE TITLE
Yaw and pitch scale

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#398]
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/util/Position.java#L52

We dont need remainder of the division because yaw and pitch can't be more than 360.

So it's should be:

``` java
 return (int) ((loc.getYaw()  / 360) * 256);
```

I would also suggest change method names to getScaledX and etc..

**Comment by turt2live** [comment]
This would be better suited as a PR considering the code has been written once for the purpose of this ticket.
