### ISSUE TITLE
Head rotation

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#399]
https://github.com/GlowstoneMC/Glowstone/blob/65b67c13dc741f4ac57548ea867e347889c4e0a4/src/main/java/net/glowstone/entity/GlowEntity.java#L397

This packet should be send only if entity instanceof EntityLiving.

**Comment by Tonodus** [comment]
Then it shouldn't be added to the update-packets list in GlowEntity, but added in GlowLivingEntity.

**Comment by turt2live** [comment]
This would be better suited as a PR.
