### ISSUE TITLE
Item pickup entities

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#4]
These act as I'm sure you expect they would. At present blocks go directly to inventory - pickup entities will be needed to make Glowstone closer to normal Minecraft.

**Comment by SpaceManiac** [comment]
I believe @akrieger is currently working on this.

**Comment by akrieger** [comment]
Yes, and it is more of a pain than you might expect :P

**Comment by turt2live** [comment]
Related to #139 (not closing as this is different enough)
