### ISSUE TITLE
GlowBufUtils

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#401]
Why GlowBufUtils not in util package?

**Comment by turt2live** [comment]
Unsure, please ask in IRC.

**Comment by SpaceManiac** [comment]
GlowBufUtils is in `net` for locality. It's got 'utils' in the name, so it can be argued it belongs in `util`, but its use is exclusively by the networking code, so I feel it belongs better in `net`.
