### ISSUE TITLE
List of severe bugs.

### ISSUE THREAD

**Issue by LegitRedStoner** [GlowstoneMC/Glowstone-Legacy#410]
- Can't put things in chests
- Can't open enchanting gui
- Can't open anvil gui
- The crafting GUI looks like this http://gyazo.com/8524d88dbba0b11c89b5de8bbb984e6d
- the word generator is interesting (broken)
- a lot of the 1.8 blocks are broken
- cant use any object that you right click with usually. eg bonemeal

And many more, I'll keep this updated.
I'm not sure if the developers already knew this, but just in case.

**Comment by ZephireNZ** [comment]
2, 3, and 4 are all fixed in #388, 5 is a duplicate of #76, 6 is probably #119, 7 is a duplicate of #325. 

Can you explain 1 more?

**Comment by jackstracey** [comment]
Hey, i have just set up a private LAN server it works fine however, water does not flow at all and it isn't lag because i can use every thing else fine, i can also break blocks perfect it is just, water will not flow.

**Comment by ZephireNZ** [comment]
@WaYsMiDNiTe Not the place to ask. However, the reason water doesn't flow is simply because Glowstone doesn't yet make water flow. Glowstone is still in heavy development, there's plenty of missing features and bugs.

**Comment by turt2live** [comment]
Closing this as duplicates of several issues. Please use the search.

**Comment by jackstracey** [comment]
@ZephireNZ okay thanks and, sorry i had no idea i just see that somebody was active and wanted to put forward my issue hoping for a response like i got

**Comment by turt2live** [comment]
@WaYsMiDNiTe You may get more help by clicking the IRC link (the button) found [here](https://github.com/GlowstoneMC/Glowstone/blob/master/README.md#docs-and-support)

**Comment by jackstracey** [comment]
@turt2live okay thanks
