### ISSUE TITLE
Locking up the main thread causes disconnection inconsistencies

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#411]
When the main thread locks up (change a few million blocks with WorldEdit), players are able to still talk to each other but the rest of the server is frozen. That's logical and makes sense. What doesn't is that when the main thread resumes (WE task done), all players are booted due to a timeout error. They are actually kicked for a timeout error and not just a socket timeout (from the looks of it). 

As a player, I'd expect one of the following to occur:

1) Be disconnected part-way through the task
2) Remain connected after the task (ideal)
3) Not have the entire server freeze due to a task (async networking, less ideal for code/performance concerns)

**Comment by ghost** [comment]
Or other thread for we...

**Comment by bendem** [comment]
@ensirius Not sure Glowstone is ready for async world modifications (pretty sure it isn't)...

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
