### ISSUE TITLE
Packet Debugging features

### ISSUE THREAD

**Issue by zml2008** [GlowstoneMC/Glowstone-Legacy#42]
I've already added toString overrides for all the packets, so this is already partially done. What's needed is some configuration for this to not log certain packets or to only log specific packets to help with targeted debugging (per-player?). The packets and codecs could also be moved out to a separate repo so they can be easily used in other proxies and stuff. This should be pretty quick to finish.

**Comment by turt2live** [comment]
I'm not sure if this is needed/wanted anymore. @SpaceManiac ?
