### ISSUE TITLE
nms plugin support?

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone-Legacy#420]
Do you think we could add a bridge or something for plugins that use nms?

**Comment by PaulBGD** [comment]
We could. But will we? No. It's not plausible.

**Comment by turt2live** [comment]
This honestly doesn't sound like a good idea to me

**Comment by dequis** [comment]
NMS breaks on every server update and plugin devs handle that every time. They could take care of glowstone as if it was another big server update.

**Comment by ZephireNZ** [comment]
The developers that use NMS understand that their plugin won't work across Minecraft versions, and certainly won't work on a different implementation. Therefore it's their problem if they haven't made it compatible with a given version or implementation, not ours.

**Comment by mastercoms** [comment]
But wouldn't it be better for servers owners who want plugins to work?

**Comment by turt2live** [comment]
Plugin authors will have plenty of time to update their plugins to Glowstone between now and first release.
