### ISSUE TITLE
Broken pull requests

### ISSUE THREAD

**Issue by gdude2002** [GlowstoneMC/Glowstone-Legacy#422]
Just a ticket to keep track of people who should be ashamed :D

Nah, but really, these PRs need fixing.

Build status on each is here: http://bamboo.gserv.me/browse/GLOW-SRV/latest
### PRs that have been failing since forever
- #189 - ReadTimeoutHander - @coelho 
- #196 - Entity gravity - @ST-DDT
- #226 - Damage - @zyuiop
- #236 - Buckets - @TomCaserta
- #286 - Ore generation - @Nickforall
- #381 - Redstone - @kaenganxt 
### PRs that have been fixed since their "shaming"
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR249-94)] #249 - Block physics - @Tonodus
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR267-91)] #267 - Skulls - @ZephireNZ 
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR272-91)] #272 - Block opacity - @nevercast 
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR358-94)] #358 - Early double chests - @socram8888
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR360-91)] #360 - Banners - @ZephireNZ 
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR385-91)] #385 - Instant block drops - @jimmikaelkael 
- [[Fixed](http://bamboo.gserv.me/browse/GLOW-SRV-PR413-88)] #413 - Damage methods - @PaulBGD
### PRs that have been closed since their "shaming"
- #277 - Events cleanup - @JeromSar 
- #331 - Scoreboard 1.8 - @games647
### Other "Naughty list" people
- @ensirius - `<ensirius> i wanna be in your naught list`
- @dequis - dx - <3

**Comment by mastercoms** [comment]
If the contributors are disinterested into fixing the issues, I can start working on them.

**Comment by gdude2002** [comment]
@mastercoms The earlier ones might be disinterested, it's hard to say though. I personally haven't heard from a few of them.

**Comment by turt2live** [comment]
@mastercoms @gdude2002 I personally consider a lack of response from the author with respect to noted issues after 7-10 days as "inactive". Feel free to use the same metric.

For updating other people's PRs:

1) Pull the changes into your own branch (and therefore your own fork)
2) Make the required changes while on that branch
3) Push the branch to your fork
4) Link the completed branch on the PR through use of a comment
- Also ping the PR assignee (if any) and the author 
- Please also include a friendly message that describes the changes you completed

5) Submit your branch as a PR to their branch with a friendly message describing the changes

At that point, either your branch will be reviewed. The author has the option to merge your changes into their PR (because of the PR you made), but they are not required to. If they do merge the changes, the now up-to-date branch will be reviewed. 

Note: If the author pulls your changes it makes the puller's job easier.

**Comment by gdude2002** [comment]
@turt2live Works for me

**Comment by dequis** [comment]
Stuff I've merged (updating this comment regularly)

(nothing here)

Outdated/invalid/etc:
- ~~#226 (Damage) - Rebased/squashed branch in comments, requires `git reset --hard` by author or resubmitting. Yes, I didn't find a better way to do it.~~ - Needs to be adapted to use PaulBGD's damage stuff.
- ~~#196 (Entity gravity)~~ - PR closed as expired, but [merged branch](https://github.com/dequis/Glowstone/compare/pr-196) still useful.

Solved:
- ~~#272 (Sided block opacity) - Fixed branch in comments, submitted PR to author~~ **Merged by author!**
- ~~#340 (Scoreboards) - Requires resubmitting against master (merges cleanly against it right now)~~. **Author resubmitted it.**
- ~~#236 (Buckets) - [Fixed branch](https://github.com/dequis/Glowstone/compare/pr-236) in comments, submitted PR to author~~ - **SpaceManiac merged it to master!**
- ~~#277 (Events cleanup) - [Fixed branch](https://github.com/dequis/Glowstone/compare/pr-277) in comments, submitted PR to author~~ - **PR closed, continued elsewhere**
- ~~#282 (Entities) - [Fixed branch](https://github.com/dequis/Glowstone/compare/pr-282) in comments~~ **Merged by author!**

**Comment by PaulBGD** [comment]
First one to fix? #hellyeah

**Comment by nevercast** [comment]
#272 has been merged with the PR that was submitted and is 'build passing', though I am not certain how to run a check style test. Thanks again @dequis for your work on that, I had somewhat forgotten of it's existence.

I invite anyone to drop comments on #272 regarding issues or fixes that need to be done. I will look over the comments tonight.

**Comment by gdude2002** [comment]
@nevercast If it's passing on Bamboo then Checkstyles is passing as well. I'll go over the PRs and bitch at people once Build 91 has finished.

**Comment by gdude2002** [comment]
And @socram8888 gets the coal for today. Better luck next time!

![](http://i.imgur.com/m0UeX7Q.jpg)

**Comment by gdude2002** [comment]
No coal this morning. Good stuff!

**Comment by dequis** [comment]
Hijacking this ticket to link to PRs that need to be resurrected: ~~#358~~ #196 #194 #272

**Comment by turt2live** [comment]
Closing this due to implementations to notify authors that stuff is broken (with improved systems coming "soon"). As for pull requests that should be resurrected, please contact me on IRC if you have suggestions and we'll go from there.
