### ISSUE TITLE
Motd

### ISSUE THREAD

**Issue by Quoll-io** [GlowstoneMC/Glowstone-Legacy#425]
If the motd is longer than this §aArazone Network Prison §0= §a play.arazone.net the server wont start

**Comment by gdude2002** [comment]
That's really not very useful. Perhaps you have a server log for us?

**Comment by ghost** [comment]
Maybe we need for better error handling add Sentry in glowstone? https://getsentry.com/welcome/

**Comment by turt2live** [comment]
3 independent parties tested this with no way to reproduce this. Please open a new issue with more information. Thanks!

**Comment by gdude2002** [comment]
To confirm: ![](http://i.imgur.com/0CTf5Wv.png)

**Comment by Quoll-io** [comment]
@gdude2002 the modt I said works however anything longer doesnt. Try this:  §aArazone Network Prison §0= §a play.arazone.net §0= §a web: arazone.net

**Comment by turt2live** [comment]
@LaughingQuoll Someone tried a 250 character long MOTD and it worked...

**Comment by gdude2002** [comment]
I think @bendem did.

![](http://i.bendem.be/2014/10/13_22-34-21.png)

**Comment by gdude2002** [comment]
@LaughingQuoll The problem is the `:` in the MOTD. Instead of `§aArazone Network Prison §0= §a play.arazone.net §0= §a web: arazone.net`, try `"§aArazone Network Prison §0= §a play.arazone.net §0= §a web: arazone.net"`. With the quotes.

**Comment by gdude2002** [comment]
@LaughingQuoll You appear to be a Java developer, so surely you'll understand what I mean when I say we could have fixed this problem a lot quicker if you had provided the error logs.

If you don't understand what I mean, maybe you should consider updating [your website](http://laughingquoll.net/)?

**Comment by bendem** [comment]
Yep, I did

**Comment by Quoll-io** [comment]
@gdude2002 I use a Linux server hosted by fluctis. Their web log does not work with glowstone so I cant see any error log.

**Comment by gdude2002** [comment]
@LaughingQuoll You can't see the server console and you don't get ftp or similar? That's.. Surprisingly bad ._.

**Comment by Quoll-io** [comment]
@gdude2002 The Fluctis server console works with bukkit and spigot as their log files have .gz at the end glowstone has .txt

**Comment by Quoll-io** [comment]
And I do get FTP

**Comment by turt2live** [comment]
Then FTP into the server, download the log, and upload it to a paste site

**Comment by Quoll-io** [comment]
Anyway issue is fixed. It was the : that stuffed it up.

**Comment by Quoll-io** [comment]
@turt2live I cant find the error because the log file is so big.

**Comment by turt2live** [comment]
It would be near the end of the most recent file.
