### ISSUE TITLE
World generation not using provided seed

### ISSUE THREAD

**Issue by TOLoneWolf** [GlowstoneMC/Glowstone-Legacy#427]
Couldn't get this to post in the other ticket #376 so had to make a new one :/
ME:

> When adding the seed option to the glowstone.yml the server will not generate with the correct seed.
> for example if you put "seed: 5555555" it generates with this seed: "1360978005" every time.
> 
> Also multiverse doesn't seem to use the seed given. It picks a random seed and edits the setting to match the world and not the other way around. I don't know if that is their error or if it is linked to this as well.
> 
> Or I could be a complete idiot and be missing a command/settting? if so sorry.

SpaceManiac commented

> In this case, 5555555 is being interpreted as a text seed and 1360978005 is its hash used as the actual seed. This is currently intended behavior. Do you definitely need 5555555 to be the actual numeric seed?
> 
> I can't say what's up with Multiverse, things should be working fine provided you're creating a brand-new world and not importing an existing world (in which case the imported seed is used). Maybe it's doing the same thing?

ME:

> why is it being interpreted as text? yes i want the number to be the number used! I want it to use the seed value i give it not make a new value from that value.
> IDK why multiverse refuses to over ride the seed glowstone is trying to use when generating a new world but I am wanting to get it to work with and without multiverse.

**Comment by dequis** [comment]
But your comment is right there...

**Comment by SpaceManiac** [comment]
Thanks for the response. I checked that Vanilla does use the number given and will update Glowstone to match.

Are you sure with Multiverse you're creating an entirely new world (no world with that name already exists)? What command are you using to create the world (including seed), and what seed do you get instead?

**Comment by TOLoneWolf** [comment]
thank you for taking time to check it out and for all your hard work.
