### ISSUE TITLE
Half A Door

### ISSUE THREAD

**Issue by domkalan** [GlowstoneMC/Glowstone-Legacy#428]
I Have Ran Into An Issue Where I Cannot Place Full Doors. I only can place half door to then have then disappear. I am running latest build.

![2014-10-13_20 27 53](https://cloud.githubusercontent.com/assets/6377796/4623604/2b5bec42-5352-11e4-85f1-bd62551523b7.png)

**Comment by ZephireNZ** [comment]
#119

**Comment by MeanMaggie** [comment]
I am experiencing this too on the latest build

**Comment by ZephireNZ** [comment]
@MeanMaggie Because it's not implemented. The PR I linked to (#119) is a more expansive list of things that are broken, which includes doors.

**Comment by MeanMaggie** [comment]
Oh, OK - still new to this, I guess

From the desk of: 

Chris Blake 
cblakework@yahoo.com

**Comment by domkalan** [comment]
Don't worry your not alone. I was very confused when i saw that to. From what i understand this project still needs alot of work.

**Comment by PaulBGD** [comment]
@domkalan from the front page: 
"Glowstone is not finished. Nothing is guaranteed to work"

**Comment by domkalan** [comment]
@PaulBGD Yeah i completely understand that...
