### ISSUE TITLE
Enable query

### ISSUE THREAD

**Issue by johnthe5th** [GlowstoneMC/Glowstone-Legacy#435]
please add
enable-query: true/false
query.port: 25565/25566
for web statistics.

**Comment by Johni0702** [comment]
Already done (#414). You might need to update if it does not yet work for you.
Please consider closing this unless there is a bug.

**Comment by johnthe5th** [comment]
I updated glowstone.jar. Don't work.

**Comment by gdude2002** [comment]
@johnthe5th What do you mean "Don't work"? What doesn't work? How doesn't it work? How do you know it doesn't work?

@Johni0702 Can you perhaps leave an explanation somewhere of exactly how that PR is supposed to work?

**Comment by johnthe5th** [comment]
Don't show enable-query: true.
I tried add server in minecraft server list.

**Comment by gdude2002** [comment]
According to the configuration guide [here](https://github.com/GlowstoneMC/Glowstone/wiki/Configuration-Guide), you should just be able to add the relevant sections to your glowstone.yml and it should just.. work.

**Comment by johnthe5th** [comment]
@gdude2002 Thanks man.
