### ISSUE TITLE
Implement blockDestroy method in the BlockType class

### ISSUE THREAD

**Issue by BarelyAPrincess** [GlowstoneMC/Glowstone-Legacy#441]
I'm creating this issue to present the need for a blockDestroy method in the BlockType class that is called from the DiggingHandler.  This method is needed for the proper removal of doors and beds.  I can make the Pull Request if you think the arguments in the example below are acceptable.

```
public void blockDestroy(GlowPlayer player, GlowBlock block, BlockFace face, Vector blockLoc) {
}
```

**Comment by SpaceManiac** [comment]
Included in 6fba836e68421088be7e960f4e26f0b3b6853a00.
