### ISSUE TITLE
Player visually hangs around after death

### ISSUE THREAD

**Issue by earthwolfgirl** [GlowstoneMC/Glowstone-Legacy#447]
I have build 91 installed on my server and My mod informed me there was two of me. I have attached images
![duplication](https://cloud.githubusercontent.com/assets/9288561/4686318/28441bca-5644-11e4-87b3-957bbf61ef80.jpg) 
![afterimage](https://cloud.githubusercontent.com/assets/9288561/4686319/2cc22a2a-5644-11e4-8efd-e84245385729.jpg)

**Comment by turt2live** [comment]
Reproduction steps? What happened to cause this? What happened prior to this?

**Comment by dequis** [comment]
I'm betting it's related to death. The vanilla client would handle something like this by not showing the second one.

What mod is this?

**Comment by turt2live** [comment]
Glowstone doesn't have full death support, so it is more than likely Glowstone if this was caused by death.

**Comment by earthwolfgirl** [comment]
So Apparently my mods decided to  /kill me while i was afk and that what caused the afterimage or duplication or what you want to call it.

**Comment by turt2live** [comment]
I've updated the issue title to better reflect the problem. Thanks!

**Comment by dequis** [comment]
Oh.. mod as in moderator? Derp.

**Comment by earthwolfgirl** [comment]
Sorry I didn't clarify that dequis. I forget that mod is also for modifications as well as moderators.

**Comment by m3rcuriel** [comment]
Hey, I can't seem to duplicate this. Can you give more information to reproduce the bug?

**Comment by turt2live** [comment]
@m3rcuriel One easy way is to get a friend and kill them.

**Comment by dequis** [comment]
Just to be perfectly clear: we are not encouraging anyone to kill their friends IRL.
