### ISSUE TITLE
Weird characters in the folder name break Glowstone's startup

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#450]
Sample path: `C:\somewhere\MyGlowstone!`

The trailing `!` breaks the script. 

Startup script used (irrelevant):

```
@echo off
java -jar "glowstone.jar"
pause
```

Exception: http://i.turt2live.com/YFFy.png

Java version:

```
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
```

**Comment by turt2live** [comment]
Other characters are reported to cause the issue as well, unknown of the set. Known case is a trailing `!` though, and it must be trailing.

**Comment by bendem** [comment]
https://github.com/GlowstoneMC/Glowstone/issues/363#issuecomment-57098626

**Comment by turt2live** [comment]
That's the workaround, but not really the fix

**Comment by bendem** [comment]
Well, there are no fix. Source: http://bugs.java.com/view_bug.do?bug_id=4730642

**Comment by turt2live** [comment]
Determined as cannot fix :(
