### ISSUE TITLE
Remote Console (Rcon)

### ISSUE THREAD

**Issue by advocaite** [GlowstoneMC/Glowstone-Legacy#451]
**Edit:** http://wiki.vg/Rcon

I would love to see this work as i cant use the server unless i have rcon as site is dependent on it. so please implement this or fix why it dose not work

**Comment by bendem** [comment]
A bit more explanation about what doesn't work would help people trying to fix it...
What are you using RCon with? Is there any error? What plateform is it being used on...?
This was supposed to be added as per #377.

**Comment by Aaron1011** [comment]
@bendem: No, #377 only added query support. RCON is a separate thing,

**Comment by bendem** [comment]
Nvm then, I thought it was the same.

**Comment by advocaite** [comment]
so this is geting added to glow stone id really like to know the site i use for my minecraft store uses rcon to communicate with my server and allows for alot of other things. if mojang use it spigot have it bukkit have it im sure glowstone would include it

**Comment by bendem** [comment]
#464
