### ISSUE TITLE
Cannot Craft (partially)

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#458]
It seems that crafting is not working correctly for me. Once I craft a table, the magic happens when crafting something else. For example, say I want to create a wooden plank, I place 4 wood blocks, and right click to get planks. When I right click only once, I am only able to get 4 sets of planks: the tile becomes blank after that. After I put them in my inventory, I try moving the 3 blocks left. This results in the block number changing from 7, and then placing them back into the crafting tile puts it back to 4, with the 4 planks i just made disappearing.

Also, if this issue was already addressed, I apologized. I searched but did not find any issue pertaining to mine.

**Comment by turt2live** [comment]
This duplicates #1

**Comment by dequis** [comment]
Eh.

Are we going to send all the window click handler bugs to #1 too?

**Comment by turt2live** [comment]
It's part of the GUI, so yes.
