### ISSUE TITLE
Importing of vanilla dimensions

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#466]
MC Vanilla client and server store nether and end worlds as subfolders inside the world folder. If the worldname_X directory (where X is nether or the_end) is missing while creating the default worlds, worldname/DIM-1 for nether or worldname/DIM1 for end should be checked. The following transformations should be applied:
- move `worldname/DIM-1/` -> `worldname_nether/`
- copy `worldname/level.dat` -> `worldname_nether/level.dat`
- move `worldname/DIM1/` -> `worldname_the_end/`
- copy `worldname/level.dat` -> `worldname_the_end/level.dat`

**Comment by turt2live** [comment]
Note: These folders can be empty if the player has not visited those dimensions.
