### ISSUE TITLE
Jenkins Server down?

### ISSUE THREAD

**Issue by firegore** [GlowstoneMC/Glowstone-Legacy#47]
i think the ci server is down

and i cannot build it myself because the repo is also down, can someone provide a working 1.0 version?

or upload the repo packages that are required to compile?

thank you for your help

**Comment by zhuowei** [comment]
I think http://ci.getspout.org/job/Glowstone/ is still up.

**Comment by SpaceManiac** [comment]
Yes, the Jenkins is down due to server software issues on Rigby's side.
