### ISSUE TITLE
PVP & entities cannot be spawned

### ISSUE THREAD

**Issue by xBlankScarx** [GlowstoneMC/Glowstone-Legacy#470]
I can't get to pvp in the server and i can't spawn mobs why?

**Comment by Aaron1011** [comment]
@xBlankScarx: Glowstone is a work in progress - many things are not implemented.

**Comment by dequis** [comment]
I lost

**Comment by turt2live** [comment]
#461 solves this partially

**Comment by turt2live** [comment]
Closing as a duplicate of #203 and #139
