### ISSUE TITLE
Support Bungee server.

### ISSUE THREAD

**Issue by laurentdu51** [GlowstoneMC/Glowstone-Legacy#478]
Hello, i'm want test your server in bungee minigames server environement.

In my fisrt test your serveur seen not compatible, can you change this on give me the good setup ?

Thankyou

**Comment by jimmikaelkael** [comment]
It should have been fixed in f8fefafa, however you should know that Glowstone still in development.

**Comment by laurentdu51** [comment]
I'm have the last build but i'm have not options in server options conf.

i'm have put the server in off-ligne mode, but i'm see not option for proxy mod :(

i'm have juste : 
11:25:02 [AVERTISSEMENT] The server is running in offline mode! Only do this if you know what you're doing.

**Comment by bendem** [comment]
You can add the `proxy-support key` in the `advanced` section of your glowstone.yml with `true` as value.
Informations about that should be added to [the wiki](https://github.com/GlowstoneMC/Glowstone/wiki/Configuration-Guide)

**Comment by laurentdu51** [comment]
Im sorry, but i'm have not found the information in the wiki.

i'm have add this key on my glowstone.yml 

advanced:
    proxy-support: true

but i'm have this error 

```
kicked: Invalid proxy data provided.
```

can you help me ?

**Comment by bendem** [comment]
I'm sorry, I know nothing about minecraft proxies, I just said that informations were missing from the wiki.

**Comment by Johni0702** [comment]
Can you provide the BungeeCord and the Minecraft version you're using?
Also make sure that you have set `ip_forward` to `true` in your BungeeCord config file.

**Comment by chno9133** [comment]
It would be perfect if glowstone allows uuid spoofing :)

**Comment by laurentdu51** [comment]
Hello.

My version on bugeeserver is : BungeeCord-Bootstrap:1.8-SNAPSHOT:"faf9034":1015

in the conf i'm have 

```
  DEV2:
    address: ********:25565
    restricted: false
    motd: '&Glowstone dev server'
```

and 

```
ip_forward: true
```

**Comment by Frobuzmumber** [comment]
I run the latest bungeecord and latest glowstone on my network and it works fine, glowstone only has one major issue with the proxy, and that is UUID's don't seem to forward properly. But aside from that, I have had no issues with glowstone and Bungeecord. I should mention that you may want to regenerate a new config file and assign your ip to 127.0.0.1 in the config file and make sure that you use the same ip in bungee's config.

**Comment by SpaceManiac** [comment]
@Frobuzmumber If you add an `advanced:` section in your config with `proxy-support: true`, and enable `ip-forward` in your bungee config, UUID forwarding should also be enabled. Please let me know if this is not the case.

These same instructions should apply to the OP. If it doesn't seem to be working, could you paste your full `glowstone.yml` and startup log?

**Comment by Frobuzmumber** [comment]
@SpaceManiac Thank you, that solved the problem and a few others. It will help with my permissions now. I also just installed plotme and that will now work properly.

**Comment by Aaron1011** [comment]
This issue should be closed now.

**Comment by SpaceManiac** [comment]
@laurentdu51 Closing, please post here again if you still have trouble.
