### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#48]
<spunkiie> 00:49:18 [SEVERE] Error during server startup.
<spunkiie> java.lang.ArrayIndexOutOfBoundsException: -2265381

I noticed this locally as well. Need to look into, will find a full stack trace soonish.

**Comment by hef** [comment]
-deleted-

**Comment by zml2008** [comment]
Pretty sure this is GlowChunk.coordToIndex. When I was cleaning up my repo, I missed the commit where I fixed coordToIndex so the broken version got into my pullrequest. It just needs to be reverted to how it was before my pullrequest.

**Comment by nthlpy** [comment]
Starts at GlowChunk.java:329

2011/12/08 14:08:42 [SEVERE] java.lang.ArrayIndexOutOfBoundsException: 32768
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowChunk.getType(GlowChunk.java:329)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowChunk.initializeTypes(GlowChunk.java:287)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:103)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowChunk.load(GlowChunk.java:231)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowChunk.load(GlowChunk.java:226)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowWorld.loadChunk(GlowWorld.java:557)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowWorld.<init>(GlowWorld.java:210)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowServer.createWorld(GlowServer.java:969)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowServer.start(GlowServer.java:450)
2011/12/08 14:08:42 [SEVERE]    at net.glowstone.GlowServer.main(GlowServer.java:114)
