### ISSUE TITLE
IP Adress please help

### ISSUE THREAD

**Issue by TheWhiteagle** [GlowstoneMC/Glowstone-Legacy#480]
i have recently discovered this new better plugin enabeled system for making servers. So i downloaded the latest build (#92) but i cant make it into a world wide server or enter my ip adress any were in the files please help

**Comment by bendem** [comment]
Add an [ip key in the server section of the glowstone.yml](https://github.com/GlowstoneMC/Glowstone/wiki/Configuration-Guide) file with the ip you want to bind to.
#452 was proposed for that reason

**Comment by TheWhiteagle** [comment]
how do i make a ip key please help

**Comment by TheWhiteagle** [comment]
i fixed it thanks for the help
