### ISSUE TITLE
Online-mode: false not working

### ISSUE THREAD

**Issue by RapidtSoftware** [GlowstoneMC/Glowstone-Legacy#487]
Whenever I set Online-mode to false in glowstone.yml file it still doesnt work in offline mode?

**Comment by dequis** [comment]
Define "still doesn't work". Getting errors? Can't log in? How are you trying to log in?

(works for me)

**Comment by SpaceManiac** [comment]
You'll have to be more specific about what you're doing to test whether offline mode works. Could you paste your `glowstone.yml` and fresh startup log in a pastebin or a comment here as well?

**Comment by turt2live** [comment]
And your startup command/script please.

**Comment by RapidtSoftware** [comment]
I mean that the cracked version of Minecraft doesn't work on the server.

Glowstone.yml: 

```
server: 
ip: 192.168.0.2
port: 13325
name: MineKart
online-mode: false
max-players: 20
whitelisted: false
motd: Welcome to the MineKart server!
shutdown-message: Server shutting down, sorry for the inconvinience!

folders:
plugins: plugins
update: update
worlds: worlds

world:
name: world
spawn-radius: 16
view-distance: 8
gen-structures: true
allow-nether: true
allow-end: true
```

Startup command:

```
java -Xmx1024M -jar Glowstone.jar -o true
PAUSE
```

Log: http://pastebin.com/NZJCxCBn

The line in glowstone.yml that says `online-mode: false` doesn't allow cracked Minecrafters to visit the servers but actually it has to.

Also in the log file there are many lines that says that some chunks couldnt load?

Please help me

**Comment by turt2live** [comment]
You enforce online mode with your startup command. Please read the documentation on the startup flags for Glowstone as offline mode is not directly supported. 

Closing as solved: startup command overrides configuration, expected behaviour.

**Comment by turt2live** [comment]
Additionally, your world seems to be seriously screwed up.

**Comment by RapidtSoftware** [comment]
Why is it screwed up, why does it say it couldnt load chunks?

**Comment by RapidtSoftware** [comment]
And thanks for the help turt2live

**Comment by turt2live** [comment]
The actual world files are corrupted somehow. From looking at the errors, it looks like the server was stopped wrongly (crash, exited without 'stop' command, system power failure, etc) while a save was occurring, corrupting the data.

**Comment by RapidtSoftware** [comment]
Can I reset it somehow?

**Comment by turt2live** [comment]
You would lose the world doing this, but what you would do is stop the server and delete the "worlds" folder next to the Glowstone JAR file. Then when you start the server it will create a new world for you.

This means you will lose the following, among other things:
- The worlds (this will reset them)
- Inventory information
- Your last position in the world

**Comment by RapidtSoftware** [comment]
Thanks for your time and help, and I haven''t even seen the world because I use cracked so its fine to reset

**Comment by turt2live** [comment]
Then it should be safe to do the steps I've mentioned above.

**Comment by RapidtSoftware** [comment]
One more question, where do I find out of the tags in the startup file to make it work?

**Comment by turt2live** [comment]
This requires some diving into the code. The applicable method can be found [here](https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/GlowServer.java#L101)

**Comment by cloud-computer** [comment]
http://nyenzo-fidel-pragata.blogspot.com/2015/03/comments-mode-on-false.html

**Comment by Ribesg** [comment]
Github has spam bots now?
