### ISSUE TITLE
Redstone Does Not Work!

### ISSUE THREAD

**Issue by XxkingassassinxX** [GlowstoneMC/Glowstone-Legacy#489]
Please Fix I Need A 1.8 Server That Can Have Plugins!

**Comment by turt2live** [comment]
Please see #116, thank you.

**Comment by dequis** [comment]
Sorry, the closest thing to a feature complete 1.8 server with plugins you'll get at the moment is the spigot protocol hack. I guess you already know how ugly that is. We're still a few months away from having complete and bug-free redstone support (very rough made up estimate based on my hopes)
