### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#490]
The world remains the same in spite of reinstalling, fall damage, and so on.

**Comment by bendem** [comment]
world: #76
fall damage: #203

**Comment by dequis** [comment]
> fall damage, and so on.

Now that's a lazy bug report.

> The world remains the same in spite of reinstalling

What does this mean? If I delete my world I get a new seed...

**Comment by tyzoid** [comment]
@Tobichenx3 Please be more specific in what is not working.

i.e. try following this template:
What is the expected behaviour?
What is the actual behaviour?
What version(s) of Glowstone does this problem occur on?
What are the steps to reproduce the issue?

**Comment by turt2live** [comment]
@Tobichenx3 Have the previous comments represented your issue adequately?

**Comment by ghost** [comment]
the dors, the redstone, the banners and the armors stand are bugged
and I don konw what is the solution

**Comment by bendem** [comment]
Doors: #119
Redstone: #116
Banners: #438
Armor stands: #139 
The solution is to wait for glowstone to be finished :wink:

**Comment by turt2live** [comment]
Closing due to lack of response from creator. Also the issue is duplicated elsewhere.
