### ISSUE TITLE
Whitelist enabled state not persisted

### ISSUE THREAD

**Issue by Cadiducho** [GlowstoneMC/Glowstone-Legacy#491]
If you enable the whitelist by command; all is Ok and work successfully but... when you restart the server; the whitelist is disabled by default. 

In addition, when you use '/whitelist on', the file Glowstone.yml remains unchanged (Boolean server.whitelisted)

**Comment by jengel3** [comment]
> In addition, when you use '/whitelist on', the file Glowstone.yml remains unchanged (Boolean server.whitelisted) 

I can't remember, but isn't this default Minecraft behavior?

**Comment by turt2live** [comment]
Vanilla behaviour is to enable (or disable) the whitelist through the server.properties file, therefore enabling (or disabling) the whitelist for the next startup.

**Comment by Cadiducho** [comment]
Tested in Vanilla and Spigot (1.7.10 both), when you execute that command in his respective configuration file the Server change the property, and works fine on restart because of it reads the whitelist status from file, and obviously not from a non static java variable.
Glowstone dont change this property. Perhaps 'you' have to override thr command from Bukkit API

**Comment by bendem** [comment]
Caused by [Server#setWhitelist(boolean)](https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/GlowServer.java#L1299) simply setting a boolean in Glowstone while Vanilla/CB updates the server.properties file as well in that method.

**Comment by SpaceManiac** [comment]
Fixed in a128bc245db36478cf496dba6ea3aa52de04b91c.
