### ISSUE TITLE
The mobs cant respawn

### ISSUE THREAD

**Issue by desquiciado** [GlowstoneMC/Glowstone-Legacy#493]
I cant see the the mobs. No mobs in all maps.

**Comment by desquiciado** [comment]
I have the version 93

**Comment by ZephireNZ** [comment]
Glowstone is still a work in progress, and mobs are not currently implemented. There is a Pull Request that covers this in #282.

**Comment by desquiciado** [comment]
a ok, sorry

**Comment by SpaceManiac** [comment]
Thanks for the report, please refer to #139 and #282.
