### ISSUE TITLE
the ammount of issues i need to place in seperate tickets is extensive

### ISSUE THREAD

**Issue by ferds814** [GlowstoneMC/Glowstone-Legacy#494]
https://www.youtube.com/watch?v=CZ1wcHLVxzs

build # 93

list:
no mobs spawn, placeable heads crash
jackolanterns and glowstone wont light up. glowstone when surounding updates light up, jackolanterns when you replace them light up.
all blocks place like wood. break as normal material
grass doesnt spread. plants don't drop anything
vines don't spread
water and lava dont flow
i have tried with and without plugins
pumpkin texture screwy
inventory is glitchy, hard to explain exactly, the video shows it
leaves do not decay
items insta-pop into inventory
respawns out of spawnpoint then teleports into spawn
 anything else is in video

**Comment by EntityReborn** [comment]
A lot of these are already known. Lighting is currently entirely clientside. No liquidflow is implemented, inventory is WIP, etc.

**Comment by ZephireNZ** [comment]
Almost all of these are known issues. In the future, please create an issue for each seperate bug _that isn't already created._
- Skulls #267 
- Lighting #100 
- Wood sounds #315 
- Plants #434 
- Block Physics (flowing, spreading, etc) #40 
- Inventory #1 
- Items #4

**Comment by ferds814** [comment]
My first time using, so i didnt know of any of these issues, and when i googled them i retreived no pages explaining in particular. annnnd i hope all goes well for glowstone, i like what they are doing. If there is known bugs it'd be nice if they stated a KNOWN:BUG section on their webpage. and presented how ZephireNZ did.

**Comment by turt2live** [comment]
@ferds814 GitHub has a search feature. 

I'm closing this for a few reasons: Duplicate of many issues and too many issues in a single ticket.

**Comment by EntityReborn** [comment]
Glowstone is still too new for extensive Google results to appear.

**Comment by SpaceManiac** [comment]
All of the issues you noted are known, listed in the other tickets linked above already. Thanks for the report regardless, I will look into providing a more obvious list of known bugs or missing features somewhere.
