### ISSUE TITLE
No Block Updates

### ISSUE THREAD

**Issue by Jovascript** [GlowstoneMC/Glowstone-Legacy#499]
On Latest Build stable build of Flowstone for Minecraft 1.8 with essetials core installed there are no block updates-
Liquids dont flow
Mobs dont spawn
sand does not fall

**Comment by turt2live** [comment]
Liquids and sand: #40 
Mobs: #139 
Thanks for the report however!

**Comment by PaulBGD** [comment]
Wait, is Flowstone that hip new software that everyone's using? Because I want in on it.

**Comment by Jovascript** [comment]
Certainly
