### ISSUE TITLE
Crafting "Rejected"

### ISSUE THREAD

**Issue by Falconida** [GlowstoneMC/Glowstone-Legacy#516]
If i try to transform wood into  woodplanks...

...the server shell give me this error(but gives me some woodplanks):
22:38:21 [INFO] user1: [rejected] WindowClickMessage(id=0, slot=0, butto
n=0, transaction=39, mode=1, item=ItemStack{WOOD x 4})

and this other error if i try to craft a workbench (and it does not give the workbench):
22:50:03  [INFO] user1: [rejected] WindowClickMessage(id=0, slot=0, butto
n=1, transaction=105, mode=1, item=ItemStack{WORKBENCH x 1})

**Comment by turt2live** [comment]
This is a known issue, please see #1 for more information.
