### ISSUE TITLE
Server lagging like crazy, chunks not loading

### ISSUE THREAD

**Issue by Clarkcj12** [GlowstoneMC/Glowstone-Legacy#519]
I just started the server, to help with the bug testing and I have noticed that there is quite a bit of chunks not loading, as you can see via the attached screenshots.
![2014-11-07_02 24 37](https://cloud.githubusercontent.com/assets/1118301/4949755/86fcf91e-664f-11e4-98c3-3d74344b9cf3.png)
![2014-11-07_02 24 51](https://cloud.githubusercontent.com/assets/1118301/4949756/8703b16e-664f-11e4-9ac9-686667141b6f.png)

OS: OS 8.1
RAM: 4GB
Server build 96

**Comment by mastercoms** [comment]
Anything in the console?
Do you use any plugins?
And what is your connection speed to the server (are you connecting to the server locally?)

**Comment by turt2live** [comment]
Were you disconnected shortly after the chunks stopped loading?

**Comment by Leymooo** [comment]
Its bug also in Spigot. Reconect is fixed this.
Its client bug.

**Comment by turt2live** [comment]
@Clarkcj12 if you are still having the issue, please describe it fully. Otherwise we can only assume you've fixed it or found an open ticket regarding the issue you're having :(

**Comment by Clarkcj12** [comment]
It seems to have fixed itself for now.

**Comment by turt2live** [comment]
Good to hear. If it happens again, please open a new ticket with as much information as possible.
