### ISSUE TITLE
Server cant run proprly with lots of plugins

### ISSUE THREAD

**Issue by andrewfer000** [GlowstoneMC/Glowstone-Legacy#522]
if I have too many plugins it will allow me to join than it will crash right away can someone plz help me fix

**Comment by mamifsidtect** [comment]
List of plugins please? And perhaps a console/server log?

**Comment by PaulBGD** [comment]
I'm going to go ahead and say it's not the amount of plugins, but instead the fact you're using an incompatible plugin.

**Comment by mamifsidtect** [comment]
@PaulBGD That's why I asked for a list of plugins and a console log :P

**Comment by mastercoms** [comment]
When you crash, are there any errors in the console?

**Comment by Etherealflux** [comment]
Does the server crash, or does the client crash? Those are very different things.

As Paul said, this is probably an issue with the plugins, rather than with Glowstone itself.

**Comment by turt2live** [comment]
@andrewfer000 if you are still having the issue, please describe it fully. Otherwise we can only assume you've fixed it or found an open ticket regarding the issue you're having :(

**Comment by gdude2002** [comment]
Closing this ticket as the author (@andrewfer000) hasn't responded since the ticket was opened ten days ago.

If you have more information to provide (as requested above) or you are still having this problem, feel free to leave a comment and/or reopen the ticket.
