### ISSUE TITLE
Whitelist issues

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#523]
Because the whitelist has so many issues, here's a list of them.

**Many of these issues may spread to other commands/features.** These are just the ones I found while testing whitelists for a PR.
- ~~Whitelist state is not correctly saved (https://github.com/GlowstoneMC/Glowstone/issues/491)~~
- Whitelisting players who have never played before show up as `null` in `/whitelist list`
- Whitelisting a player that does not exist still whitelists them (and prints a pretty exception to the console). Example: `/whitelist add {test}`

I'll add more as I find them. Existing tickets should remain open for points of reference.

**Comment by m3rcuriel** [comment]
Issue #491 is fixed as of commit https://github.com/GlowstoneMC/Glowstone/commit/a128bc245db36478cf496dba6ea3aa52de04b91c

**Comment by turt2live** [comment]
Finally updated the description. Completely forgot to do so.

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
