### ISSUE TITLE
Sign text issues (when loading vanilla maps?)

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#528]
While testing a PR, turt2live loaded a texture pack test map in which the signs had text like this in glowstone, but not in vanilla:

```
null
"Armor"
null
null
```

or 

```
""
"Armor"
""
""
```

Additionally, lines with long text had words disappear from them:

```
""
"Brown
""
""
```

Was supposed to be `Brown Mushroom`. The red mushroom sign next to it displayed as `"Red Musroom"` (sic), so it's probably related to text length.

**Comment by turt2live** [comment]
Also sometimes color codes are not correctly handled. They display the "textual" value.

Edit: Here's code that works on glowstone, but if somehow implemented the same way on vanilla (possibly craftbukkit?) will cause issues in Glowstone when the map is used. http://i.turt2live.com/OYL9.txt

**Comment by SpaceManiac** [comment]
To wit, the cause of this is the storage change in 1.8 maps where sign strings are now serialized in their json form. A reasonable fix would first try to parse the line as a JsonValue (possibly through `TextMessage#decode`) or fall back to the raw text (in case of 1.7 maps). It may also be worth checking if an NBT field indicates whether the messages are json or not. Of course saving the lines should be changed also.
