### ISSUE TITLE
Regression in invisibility

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#530]
Previously it was possible to become vanished using a plugin, now that behaviour is not fully functional.

_Pending determination of when regression occurred_

**Comment by Johni0702** [comment]
Calling `Player.hidePlayer(Player)` and `Player.showPlayer(Player)` still works for me and has the expected result. What plugin was used to test this?

**Comment by turt2live** [comment]
A plugin that used exactly those methods. The behaviour is not fully functional when tested, will test again.

**Comment by dequis** [comment]
vanishnopacket.

**Comment by turt2live** [comment]
For reference before reporting the issue I did test with an independent plugin to remove the possibility of plugin failure. Source is at home though, so I can't upload right now :(

**Comment by Johni0702** [comment]
Just tried it with VanishNoPacket and I can confirm that it's not working.
I used ScriptCraft (to call those methods directly): `/js server.getPlayer("test").hidePlayer(self)`
I'll look into it.

**Comment by Johni0702** [comment]
Nvm. I cannot reproduce it. What I took as the bug above was just the fact that OPs can see other OPs (they disappear shortly and reappear after a few ticks) and the fact that VanishNoPacket didn't update it's permissions cache when I (de-)opped myself which confused me quite well.
Can anyone provide a step by step description of how to reproduce this?

**Comment by dequis** [comment]
> What I took as the bug above was just the fact that OPs can see other OPs (this disappear shortly and reappear after a few ticks) 

I think that's exactly what's going on here. So craftbukkit has the same behavior? Derp. Maybe we can close this.

**Comment by Johni0702** [comment]
@turt2live You can probably close this now unless you experienced something different than what dequis and I did.

**Comment by turt2live** [comment]
I have yet to do my own further independent testing. Once I do then this will be updated accordingly.

**Comment by SpaceManiac** [comment]
Any word on whether this is actually still an issue?

**Comment by dequis** [comment]
Fairly sure it was never an issue, just VNP's handling of permissions and OPs resulting in other OPs being visible

**Comment by SpaceManiac** [comment]
Closed until otherwise shown, then.
