### ISSUE TITLE
World.getBlockAt wrap around

### ISSUE THREAD

**Issue by socram8888** [GlowstoneMC/Glowstone-Legacy#534]
I've noticed while implementing the sponge block that getBlockAt returns block at (Y & 0xFF), so for a block outside the valid chunk range like -1, it wraps around to 255.

Shouldn't this method either throw an error, or map to a non-existant (ie void) block? Because these may cause weird stuff with physics, like water falling from the sky if somebody in creative makes a hole in the bedrock.

**Comment by turt2live** [comment]
This is expected behaviour.
- Tested with [this plugin](http://i.turt2live.com/HW1A.jar) ([source](http://i.turt2live.com/RIqx.txt)).
  - Command to activate: `/test` (does not require an online player)

**Results**
- Glowstone: Behaviour mentioned above
- CraftBukkit 1.7.10 (1_7_R4): Behaviour mentioned above

_Edited: Included testing results_

**Comment by socram8888** [comment]
I am aware that it behaves like that also in CraftBukkit. But in that case the org.bukkit.World@getBlockAt interface has a wrong description, since it says that _it returns block at given coordinates_. For a non-existant block, I'll expect it to return a dummy AIR block (void).

Doing a binary AND is not only hacky but it's also not future-proof.

**Comment by turt2live** [comment]
Changing the return value potentially breaks plugins, so I doubt that will change. As for the implementation, I suggest you talk it over with @SpaceManiac.

**Comment by socram8888** [comment]
I am not talking about throwing an exception or returning null, both which are potentially breaking.

I am talking about returning a dummy block: a block that setting its type does nothing, and getting the type returns air. This is how the original game behaves: blocks outside the valid range are air, and that can't be changed, and also, according to the method's own definition, how it should work.

**Comment by turt2live** [comment]
That still has the potential to break plugins... Its expected behavior now.

sent from mobile
