### ISSUE TITLE
crafting problem

### ISSUE THREAD

**Issue by kostas978** [GlowstoneMC/Glowstone-Legacy#538]
in my server i have crafting problems with crafting table there is any solution for this problem?
![2014-11-12_13 10 39](https://cloud.githubusercontent.com/assets/9694238/5009226/6b0b3d2a-6a6d-11e4-956d-70813f2cf2a9.png)

**Comment by jimmikaelkael** [comment]
You should know that Glowstone is still in development. There are many things that still needs to be fixed or implemented.

**Comment by kostas978** [comment]
so there is no solution for this?

**Comment by jimmikaelkael** [comment]
You should really give more details on the problems you were facing.

**Comment by turt2live** [comment]
Looks to be a duplicate of #1. What were the issues you had?

**Comment by turt2live** [comment]
@kostas978 if you are still having the issue, please describe it fully. Otherwise we can only assume you've fixed it or found an open ticket regarding the issue you're having :(

**Comment by gdude2002** [comment]
As the author of this ticket hasn't responded for ten days, I'm going to close this ticket.

Feel free to comment or re-open this ticket if you continue to have problems, @kostas978
