### ISSUE TITLE
Citizens2 Not Working

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#542]
When try to use /npc...
Nothing happens.
I have tried reinstalling it and other Citizens2 commands
Still nothing happens
I don't think it will make a difference (it hasn't so far) but I am using a mac.

**Comment by Aaron1011** [comment]
Glowstone currently doesn't have entity support (though there's an open PR for it). Until that (and probably other things) is implemented, Citizens won't work.

**Comment by turt2live** [comment]
Duplicate of #139

**Comment by ZephireNZ** [comment]
Aside from entities not being implemented, it seems Citizens also relies on NMS. Doubly closed :P
