### ISSUE TITLE
Entities not spawning/being shown 

### ISSUE THREAD

**Issue by BiscuitBro** [GlowstoneMC/Glowstone-Legacy#555]
When my friend and i were playing on a server i make with glowstone we noticed that any entity would not appear/spawn.

**Comment by gabizou** [comment]
Entities are not implemented yet. There is a PR already open for them: https://github.com/GlowstoneMC/Glowstone/pull/282

**Comment by BiscuitBro** [comment]
Oh ok sorry. i didn't see that.

**Comment by turt2live** [comment]
As mentioned, see #282 (ticket: #139)
