### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by BiscuitBro** [GlowstoneMC/Glowstone-Legacy#556]
When ever i place any block of any type it always has the same sound when being placed, but all the other sounds were fine. Then i made a test server and deleted this sound.class file then the block being placed sound was gone (there was no sound when placing a block (after i deletes sound.class)). so my guess is is that the sound.class either doesn't have all the sounds or it has a bug.

**Comment by dequis** [comment]
Duplicate of #99 

> deleted this sound.class file

That's the weirdest way to try to fix a bug.

**Comment by BiscuitBro** [comment]
well i deleted it to see if it was the source or not

**Comment by turt2live** [comment]
As mentioned, see #99.
