### ISSUE TITLE
problem on restarting or stopping console

### ISSUE THREAD

**Issue by MuscleMan111** [GlowstoneMC/Glowstone-Legacy#559]
whenever I click on the console to restart my test server, it comes up with this message22:00:24 [SEVERE] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already in use?
This is very annoying as I want to test out some bucket plugins.
I have no idea if this is a bug or if it is just me being me, but either way, I would like a reply.

**Comment by gdude2002** [comment]
You've already got a server running on the port you have configured. Take a look at your list of processes (For example in the task manager) and make sure there are no Java processes running, and try again.

**Comment by SpaceManiac** [comment]
Also, make sure you haven't set `server.ip` in your config unless you're sure you need to. Most of the time you should leave it blank.

**Comment by MuscleMan111** [comment]
ok, I have got rid of any other servers running on the same port, and i am still getting the problem. I wrote :25565 as my ip

**Comment by gdude2002** [comment]
If you have a line starting with `ip` in your `config/glowstone.yml` file, please remove it and try again.

**Comment by MuscleMan111** [comment]
remove the line? Or just the ip in the line

**Comment by gdude2002** [comment]
Remove the entire line.

**Comment by MuscleMan111** [comment]
still not working :/

**Comment by gdude2002** [comment]
You're still getting the same problem? Please check [our new FAQ page](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions), and if that doesn't work, go to [Github Gist](https://gist.github.com), paste your `glowstone.yml` file, and give us the link here.

**Comment by Verald** [comment]
i have the same problem. still getting problem
here is the link: https://gist.github.com/Verald/4fd79b59c7669b4a4212

**Comment by gdude2002** [comment]
@Verald you have your own ticket open at #589, please use that.

Closing this ticket due to inactivity.
