### ISSUE TITLE
FAQ section on wiki

### ISSUE THREAD

**Issue by gdude2002** [GlowstoneMC/Glowstone-Legacy#560]
I'm [compiling an FAQ page on the wiki](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions) - what kind of things should we put in there?

**Comment by gdude2002** [comment]
`<bendem> missing libs, nms/obc class not found, missing <insert not implemented feature>, world gen is broken`

**Comment by gdude2002** [comment]
Whoops, didn't mean to close that.

**Comment by gdude2002** [comment]
Alright, implemented @bendem's suggestions, and added a section about creating tickets and asking us on IRC.

**Comment by dequis** [comment]
From the point of view of a lazy user: TL;DR

The current answers seem good and explain a lot, which is good, but they also _look like too much to read_.

**Comment by SpaceManiac** [comment]
Since the FAQ page exists and seems fairly stable, I think this can be considered closed.
