### ISSUE TITLE
My server cant bind to the address.

### ISSUE THREAD

**Issue by BiscuitBro** [GlowstoneMC/Glowstone-Legacy#561]
Help when ever i run the  server it doesn't work. This it what comes up:

21:57:40[SEVER] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already in use?
at net.glowstone.GlowServer.bind(GlowServer.java:438)
at net.glowstone.GlowServer.main(GlowServer.java:93)

I looked for server that was running but i couldn't find anything!

**Comment by gdude2002** [comment]
There are a couple reasons this could be happening. Please read our new [Frequently Asked Questions page](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions) and come back here if it was unable to solve it.

**Comment by gdude2002** [comment]
Same problem as #559

**Comment by BiscuitBro** [comment]
Thank you so much it worked!

**Comment by gdude2002** [comment]
No problem. Feel free to open another ticket if you have any more issues.
