### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by QuantumvVex** [GlowstoneMC/Glowstone-Legacy#562]
Hi there. An issue I found is when I launch the newest version of glowstone, the world that it generates is all birch and oak trees, on areas of land surrounded by water.

**Comment by gabizou** [comment]
It's a known missing feature: refer to https://github.com/GlowstoneMC/Glowstone/issues/76

**Comment by gdude2002** [comment]
As @gabizou says, this is simply not done yet. Refer to [this page](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#world-generation-is-broken) for more information.
