### ISSUE TITLE
Failed to bind to address

### ISSUE THREAD

**Issue by Christian4432** [GlowstoneMC/Glowstone-Legacy#563]
13:57:47 [SEVERE] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already use?

```
                     at  net.glowstone.GlowServer.bind<GlowServer.java:415>
                     at  net.glowstone.Glowserver.main<GlowServer.java:91
```

**Comment by Christian4432** [comment]
Please Help

**Comment by greatman** [comment]
https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#failed-to-bind-to-address-maybe-it-is-already-in-use

**Comment by gdude2002** [comment]
As with #559 and #561,  please see the link that @greatman gave you.

**Comment by gdude2002** [comment]
As this is a duplicate of #559, I'm going to close it. Please go there if you continue to have this problem after following the instructions.

**Comment by Christian4432** [comment]
its still not working

**Comment by gdude2002** [comment]
How is it still not working? Is it the same problem? Did you try the steps in #559, #561, and https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#failed-to-bind-to-address-maybe-it-is-already-in-use ?

**Comment by Christian4432** [comment]
yes

**Comment by gdude2002** [comment]
Are you running some other Minecraft server at the same time?

**Comment by Christian4432** [comment]
no

**Comment by Christian4432** [comment]
i have killed all java process

**Comment by Christian4432** [comment]
dont have ip in glowstone.yml

**Comment by gdude2002** [comment]
If you've killed all Java processes, and you're /still/ getting that error, then you have some other program that's running on that port.

**Comment by Christian4432** [comment]
yes

**Comment by gdude2002** [comment]
So you're going to have to work out what's doing that. What OS are you running? Windows 7/8? Mac? Linux?

**Comment by Christian4432** [comment]
Windows 7

**Comment by Christian4432** [comment]
can you post a clip? to how to do it

**Comment by gdude2002** [comment]
Okay, open the task manager, go to the performance tab and hit the resource manager button. Go to the networking tab, and look at the "Listening ports" list.

Somewhere in the list should be a process with a "Port" entry of 25565. What is it?

**Comment by gdude2002** [comment]
It may look something like this.

![](http://i.imgur.com/DS8GG7n.png)

**Comment by Christian4432** [comment]
there found it?

**Comment by gdude2002** [comment]
Alright, so what does it say under "image"?

**Comment by Christian4432** [comment]
can i post a photo?

**Comment by Christian4432** [comment]
the uttorent

**Comment by gdude2002** [comment]
Ah, so utorrent is doing it. So if you close utorrent, you should be able to run Glowstone.

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5162529/5954728a-73fb-11e4-9fb1-9416ae3ebe3c.png)

**Comment by gdude2002** [comment]
Alternatively, you can change the port either utorrent or Glowstone is using.

**Comment by Christian4432** [comment]
ahhh

**Comment by Christian4432** [comment]
gdude are you the admin

**Comment by Christian4432** [comment]
working

**Comment by Christian4432** [comment]
ready for connections

**Comment by gdude2002** [comment]
I'm just someone who helps out with the GitHub tickets and helps to run [the forum](https://forums.glowstone.net).

Glad you got it working - Let us know if you have any more problems \o/

**Comment by Christian4432** [comment]
w8

**Comment by Christian4432** [comment]
its to slow

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5162559/cc22ca64-73fb-11e4-9532-438a26974543.png)

**Comment by gdude2002** [comment]
It took all of six seconds to start, how is that slow?

**Comment by Christian4432** [comment]
i d k

**Comment by Christian4432** [comment]
can you give me some run codes

**Comment by Christian4432** [comment]
please reply

**Comment by gdude2002** [comment]
What are "Run codes"?

**Comment by Christian4432** [comment]
the codes that you are going to use in run.bat

**Comment by gdude2002** [comment]
They're on the installation page.

https://github.com/GlowstoneMC/Glowstone/wiki/Installation#windows

**Comment by dequis** [comment]
this is the weirdest chat why can't i submit messages when pressing enter

**Comment by dequis** [comment]
please respond

**Comment by gdude2002** [comment]
@dequis this is not live support, go back to your yoghurt

**Comment by Christian4432** [comment]
???

**Comment by Christian4432** [comment]
its not working

**Comment by Christian4432** [comment]
w8 will portforward it???

**Comment by Christian4432** [comment]
mean will i portforward it???

**Comment by Christian4432** [comment]
fast

**Comment by gdude2002** [comment]
Yeah, you'll need to port forward if you want other people to play.

**Comment by Christian4432** [comment]
i know

**Comment by Christian4432** [comment]
its still not working

**Comment by Christian4432** [comment]
this is the code i using>>> java -Xmx1024M -jar Glowstone.jar -o true
PAUSE

**Comment by gdude2002** [comment]
What isn't working exactly?

**Comment by Christian4432** [comment]
dont know

**Comment by gdude2002** [comment]
So then how do you know it isn't working? ._.

**Comment by Christian4432** [comment]
i said dont know

**Comment by gdude2002** [comment]
But you just said it isn't working..?

**Comment by Christian4432** [comment]
yeah i know

**Comment by Christian4432** [comment]
sorry... because im not foriener

**Comment by Christian4432** [comment]
im just a filipino

**Comment by gdude2002** [comment]
What language do you speak?

**Comment by Christian4432** [comment]
tagalog

**Comment by gdude2002** [comment]
I'll try to use Google translate.

Paano ko malalaman mo na mayroon kang problema?

**Comment by Christian4432** [comment]
nalaman ko lang ang problema na may lumabas na ready for connections at matagal

**Comment by gdude2002** [comment]
Mayroon na iyong sinubukang port forward?

**Comment by Christian4432** [comment]
oo.

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5163148/fe4fabd6-7402-11e4-8893-5917d45c2d60.png)

**Comment by gdude2002** [comment]
Ano ang ibig mong makuha kung nag-type ka ng "ip" sa google.com?

**Comment by Christian4432** [comment]
hindi

**Comment by gdude2002** [comment]
Hmm .. Ano ang iyong IP address?

http://whatismyipaddress.com/

![](http://i.imgur.com/W9KJMjD.png)

**Comment by Christian4432** [comment]
done

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5163227/0ae5387e-7404-11e4-9d9e-ae5986e204cd.png)

**Comment by gdude2002** [comment]
Hindi, sa tingin ko na mayroon kang mga tamang IP address bago, kailangan kong malaman ang isang ito kaya maaari ko ba itong subukan.

**Comment by gdude2002** [comment]
Sa tingin ko ang wika barrier ay gumagawa ito mahirap, alam mo ang sinuman na nagsasalita sa mas mahusay na Ingles?

**Comment by Christian4432** [comment]
just use english language

**Comment by gdude2002** [comment]
Alright..

Yeah, I think the IP you had before was probably correct - 192.168.254.188 is a local address.

222.127.174.21 is the one other people should connect to.

Does it work if you try to connect to 127.0.0.1?

**Comment by Christian4432** [comment]
118

**Comment by gdude2002** [comment]
Sorry, yeah, 118.

**Comment by Christian4432** [comment]
no

**Comment by gdude2002** [comment]
So you open Minecraft, type in `127.0.0.1` and.. You get an error? What error, if so?

**Comment by Christian4432** [comment]
no

**Comment by Christian4432** [comment]
i open localhost

**Comment by gdude2002** [comment]
And what happens?

**Comment by Christian4432** [comment]
error

**Comment by Christian4432** [comment]
the problem is this

**Comment by gdude2002** [comment]
Oh, wait, hold on, did you close the window that opens when you double-click the start.bat file? You need to leave that open.

**Comment by Christian4432** [comment]
no

**Comment by Christian4432** [comment]
the problem is the ready for the connection

**Comment by gdude2002** [comment]
That means you can connect to it, though. It's finished loading at that point.

**Comment by Christian4432** [comment]
java.lung.nullpointerexception

**Comment by gdude2002** [comment]
Can you paste a screenshot/photo or the entire log?

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5163612/a31135f4-7408-11e4-9acc-f622ac64caeb.png)

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5163615/aab36138-7408-11e4-8d83-e1fc6465b645.png)

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5163620/b4c2db04-7408-11e4-8401-0fd65b16a601.png)

**Comment by gdude2002** [comment]
Could you try this Glowstone JAR? It was built about an hour ago; it looks like you're using an old one. 

http://ci.chrisgward.com/job/Glowstone/101/artifact/build/libs/glowstone.jar

**Comment by Christian4432** [comment]
its not working

**Comment by gdude2002** [comment]
Same problem?

**Comment by Christian4432** [comment]
yes

**Comment by Christian4432** [comment]
w8 is the glowstone worked in cracked??

**Comment by gdude2002** [comment]
It should work in offline mode, but we can't provide support for that.

**Comment by Christian4432** [comment]
ahhh

**Comment by Christian4432** [comment]
i cant connect to my server

**Comment by turt2live** [comment]
@Christian4432 The error you are getting implies that something happens on the server after you connect. Can you provide the following screenshots in order please?
1. When the server says "Ready for connections"
2. After you get "java.lang.NullPointerException"

Thanks

**Comment by Christian4432** [comment]
HUH???

**Comment by turt2live** [comment]
After you see the error in Minecraft, open the console and take a screenshot

**Comment by Christian4432** [comment]
1st
![image](https://cloud.githubusercontent.com/assets/9895971/5177579/9582af56-7496-11e4-9d20-28ad9a19e17e.png)

**Comment by Christian4432** [comment]
2nd
![image](https://cloud.githubusercontent.com/assets/9895971/5177586/af836d5a-7496-11e4-9f87-b213afe7d9a2.png)

**Comment by Christian4432** [comment]
3rd
![image](https://cloud.githubusercontent.com/assets/9895971/5177596/c64ff2ba-7496-11e4-8196-45fec49a5f96.png)

**Comment by turt2live** [comment]
Just to confirm: the server you are connecting to is "localhost" as the IP?

**Comment by Christian4432** [comment]
yes

**Comment by Christian4432** [comment]
reply

**Comment by turt2live** [comment]
Ok, follow these steps:

1) Close Minecraft but leave the server running
2) Open the Minecraft launcher and click "Edit Profile" in the bottom left
3) Edit "Launcher visibility" to look like this: ![img](http://i.turt2live.com/Wlpl.png)
4) Click "Save Profile"
5) Click "Play"
7) Try to connect to your server again
8) After you get the error, open the grass block on your taskbar: ![img2](http://i.turt2live.com/na4W.jpg)
9) Take a screenshot of that program

**Comment by Christian4432** [comment]
is it ok in cracked launcher

**Comment by turt2live** [comment]
A cracked launcher is not compatible with Glowstone and is therefore not supported.

**Comment by Christian4432** [comment]
ahh...WEW

**Comment by Christian4432** [comment]
thats the problem

**Comment by turt2live** [comment]
We can't support you on this, you have to use the Mojang launcher.

**Comment by Christian4432** [comment]
why they can make a cracked server

**Comment by turt2live** [comment]
It is unsafe to do so. 

Does your cracked launcher have a log?

**Comment by Christian4432** [comment]
dont have money to buy

**Comment by Christian4432** [comment]
log?

**Comment by turt2live** [comment]
What client do you use.

**Comment by Christian4432** [comment]
im using terraminingmc launcher

**Comment by turt2live** [comment]
That launcher is not compatible with Glowstone at all. You have to use the Mojang one, sorry.

**Comment by Christian4432** [comment]
![image](https://cloud.githubusercontent.com/assets/9895971/5177700/8ef3e2d4-7498-11e4-9f33-331402d40d4a.png)

**Comment by Christian4432** [comment]
i wish that i have an account

**Comment by Christian4432** [comment]
do you have extra accounts

**Comment by Christian4432** [comment]
can i borrow it?

**Comment by turt2live** [comment]
No one is going to give out accounts

**Comment by Christian4432** [comment]
hehehhehe

**Comment by Christian4432** [comment]
soorry

**Comment by turt2live** [comment]
I'm locking this because the launcher you are using is not supported by any means.

**Comment by Christian4432** [comment]
how much money to buy account

**Comment by turt2live** [comment]
You can get more information at mojang.com
