### ISSUE TITLE
Gamemodes 4-Infinity do not exist

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#565]
But they do in Glowstone!

`/gamemode 9` -> Survival mode (can be any number ![0-3])

**Comment by bendem** [comment]
I'd say this is intended seeing the [bukkit side](https://github.com/GlowstoneMC/Glowkit/blob/master/src/main/java/org/bukkit/command/defaults/GameModeCommand.java#L59).

**Comment by maxov** [comment]
I tested this in vanilla and it works the same way. Gamemodes 4-infinity all point to gamemode 0(Survival).

**Comment by turt2live** [comment]
I didn't get that behaviour, I got a rejection message

**Comment by maxov** [comment]
I am using MC version 1.8.1 on a creative world with commands enabled. The 'rejection message' of `<player> already has game mode 0` means that MC treats other gamemodes > 3 like gamemode 0, unless you are getting a different message.

**Comment by turt2live** [comment]
Testing 1.8.1 is kinda counter productive as Glowstone is 1.8.0, but either way:

When I tested it on a Mojang 1.8.0 server in creative mode as an operator I received a rejection message for trying to set my gamemode to 4, my gamemode was not set to survival.

**Comment by maxov** [comment]
You're right. For reference, this is what the gamemode messages look like:
![gamemodes](http://puu.sh/d55Mw/15f794f8f4.png).

**Comment by turt2live** [comment]
I'm still undecided if it's really an issue, I just opened the ticket cause it doesn't match.

**Comment by turt2live** [comment]
Paging @SpaceManiac for comment on whether this is valid as a ticket

**Comment by SpaceManiac** [comment]
The issue is minor, but I'd say it stands. Really it's just `GameModeCommand` that needs to get updated. Probably a case for "spectator" should be added to the command as well.

**Comment by turt2live** [comment]
If that's the case, then I suggest [this](https://github.com/Turt2Live-DEV/Bukkit/commit/e467a733b15b16050fbb52516de6cab49d9ef264) as a proposed solution. The error message differs, but I don't feel as though we need to be as explicit with this particular command. 

( ref: e467a733b15b16050fbb52516de6cab49d9ef264 )

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
