### ISSUE TITLE
Crafting problem (items are deleted)

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#573]
Ok I am running the latest stable glowstone.jar and I made a crafting table and weather I am in the crafting table or the smaller crafting area by just pressing E if I right click on the crafted item say I was making wood planks and right clicked to make a stack it just does not work. It doesn't take away from the material side and deletes what I made.

**Comment by turt2live** [comment]
There are known issues with many components of Glowstone, including crafting. Please see #1 for more information on your issue.

Glowstone is intended for development purposes only. It is not currently a drop-in replacement for any server software and is missing several features. A partial list of known-working features can be found [here](https://github.com/GlowstoneMC/Glowstone/wiki/Current-Features).
