### ISSUE TITLE
Lakes are just... idk.

### ISSUE THREAD

**Issue by Techy4198** [GlowstoneMC/Glowstone-Legacy#576]
I can see that the lakes populator is taken from somewhere, as I used it in one of my own Bukkit plugins a while back. I recommend attempting to replace it with a vanilla-based lake populator, or am I missing something here? The current world generation is just a place holder right? Also if you need code, I can help code one based off the vanilla one from Bukkit. One copy from an old plugin I made is heavily modified anyway (to make it work as a custom block populator), but still obfuscated, but that's not a problem for me to fix. If necessary, in the process of making it perfectly legal, I can reverse-engineer it, write it in pseudo-code, then remake it from scratch.

**Comment by jimmikaelkael** [comment]
Some work is currently being done concerning world generation.
I will most probably enhance lakes in #572.

**Comment by Techy4198** [comment]
I see that you're adding tons more decorators/populators/whatever, but what's happening about the actual terrain? Are we gonna see dirt beaches and mega broken dungeons for much longer? Also I see that there's a cave generator but it doesn't seem to work.

**Comment by jimmikaelkael** [comment]
I believe @gratimax is taking care of terrain/world gen, he will take care of caves too I guess with perlin worms. (#471)

**Comment by bendem** [comment]
@Techy4198 people are working on a vanilla like world gen, but Glowstone isn't based on vanilla code and shouldn't contain any part of the vanilla code. Thus, contribution based on reverse engineering is not likely to get pulled.
If you want to make a world gen plugin based on the vanilla code, it will surely be greatly appreciated tho. :wink: 
That being said, @turt2live or @SpaceManiac may think otherwise.

**Comment by turt2live** [comment]
@bendem A plugin that uses vanilla as a world generator exists.

As for this ticket, it's a duplicate of #76. We cannot use the vanilla generator, but world generation is an ongoing, and frankly fairly low priority, concern.

**Comment by Techy4198** [comment]
So how, in any way, is this supposed to be an alternative to Bukkit? It had better implement an as-close-as-possible replica of the vanilla world generator, in order for seeds to work as expected. Otherwise, this project will get a lot of hate, especially from people like me, who want nothing more than a replacement for Bukkit. As long as there are no legal issues, I don't care what code goes into it.

**Comment by turt2live** [comment]
CraftBukkit used vanilla, we cannot. We'll try to get close to vanilla, but
do not expect full compatibility.

sent from mobile

**Comment by maxov** [comment]
From my experience, Vanilla-like generation down to the block in seeds is impossible unless we copy the weirdness that is MC world generation _exactly_. At that point it _does_ become a legal issue but is the only option to get the exact same world generation. Most likely Glowstone will have its own vanilla-like generator and a world generator based on MC would be available in a plugin that uses MC sources directly.

**Comment by turt2live** [comment]
We will not likely publish the plugin though, it would be a community
plugin. By the way, it already exists.

sent from mobile

**Comment by Techy4198** [comment]
what do you mean you won't publish it? Also, how up to date is it?

**Comment by Techy4198** [comment]
Besides, if the server doesn't aim to get as close to vanilla world gen as possible, with no direct code copies, then I am going to knock this off my list of Bukkit replacements. I do hope Sponge implements a much better world gen, although this might be a big part of it. Impossible to know ahead of time.

**Comment by turt2live** [comment]
Glowstone likely won't publish it for legal concerns. As for how up to date it is, you'll have to ask the author. 

Glowstone is aiming for several targets, one of which is vanilla. We do aim for API compatibility for Bukkit (meaning behaviours of CraftBukkit), but vanilla is also a reasonable target where applicable when it comes to game behaviour. 

I do appreciate your interest in Glowstone, but what is concerning is the number of threats to use another project (or lack thereof) when we can't conform to your standards. We do attempt to meet a fairly strict set of requirements, but some cannot be matched for legal, development, or environmental reasons. We cannot meet all demands uttered, although we do try to be sane in our decisions.

With that, I see this conversation going no further as it's just becoming a circle of complaining and explanation. If you have further questions or concerns, please join us on IRC (information is in the README).

Locked.
