### ISSUE TITLE
Guava v14.0 breaks compatibility with some plugins

### ISSUE THREAD

**Issue by socram8888** [GlowstoneMC/Glowstone-Legacy#578]
Namely, PermissionsEx, and maybe others, whose binaries are compiled against v10.0. Google changed the signature and removed a few methods, so these can't be used without manually patching and recompiling them.

You can't download Guava v10.0 and add it to the classpath since it clashes with Glowkit's built-in (shadowed) Guava.

I see three options:
- Downgrade to Guava v10.0. Easiest bet, but you lose any kind of perfomance improvements or bugfixes you may get by using the latest build.
- Use the GuavaCompat10 hack I made half a year ago when I faced the same problem with SportBukkit (which also used v14.0 and also failed): https://github.com/socram8888/GuavaCompat10. It's a series of patches that readd a few missing methods, enough to allow PEX to run.
- Upgrade to v18.0. It won't fix the broken plugins but at least we would be compiling against the latest version available.

**Comment by gdude2002** [comment]
How's your third point a fix, then?

I think we'll probably have to go with compat hacks, but honestly, I would much prefer if these plugins just updated.

**Comment by Ribesg** [comment]
Guava was in CB, not B, right?
Then can't you just add it as a lib like Log4J and others?

**Comment by dequis** [comment]
> Then can't you just add it as a lib like Log4J and others?

See:

> You can't download Guava v10.0 and add it to the classpath since it clashes with Glowkit's built-in (shadowed) Guava

**Comment by dequis** [comment]
```
09:48 < Socram8888> err i'm stupid
09:48 <@g> ?
09:48 < Socram8888> i don't remember where i saw guava v14, but glowkit is using guava v10
09:48 < Socram8888> i'm closing the issue
09:48 <@g> lol.
09:49 < Socram8888> i was absolutely sure i saw guava 14 somewhere, though
09:50 <+dx> lol
```
