### ISSUE TITLE
Glowstone server error 

### ISSUE THREAD

**Issue by Djani9892** [GlowstoneMC/Glowstone-Legacy#582]
Please help me...

18:24:07 [SEVERE] Error during server startup.
java.lang.RuntimeException: Failed to bind to address. Maybe it is already in us
e?
        at net.glowstone.GlowServer.bind(GlowServer.java:440)
        at net.glowstone.GlowServer.main(GlowServer.java:95)

**Comment by gdude2002** [comment]
We've got an FAQ topic for this, please click here to view it: https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#failed-to-bind-to-address-maybe-it-is-already-in-use

**Comment by Djani9892** [comment]
I dont understand.. :( Do you have video?

**Comment by Djani9892** [comment]
ip: 255.255.255.255 or ip: 192.168.0.1
    port: 25565
    name: Glowstone Server ?

Binding to address: /192.168.0.1:25565...

**Comment by gdude2002** [comment]
@Djani9892 You've got something running on that port already - probably a Glowstone server running already. You'll need to close it before you can run Glowstone again.

**Comment by Djani9892** [comment]
I change port again see it error... i try with 25566,8899,25555 etc...

**Comment by gdude2002** [comment]
@Djani9892 Did it fail each time?

**Comment by Djani9892** [comment]
No?

**Comment by gdude2002** [comment]
@Djani9892 So, is the problem fixed?

---

Pinging @greatman here as he asked for it.

**Comment by Djani9892** [comment]
I start server.. Yes problem fixed but now i see error when try to join server: failed to login invalid session (try restarting your game)

**Comment by gdude2002** [comment]
@Djani9892 And, did you try restarting your game? Closing the launcher and trying again?

**Comment by Djani9892** [comment]
YES! WORK! FIXED :) Thank YOU!

**Comment by gdude2002** [comment]
You're welcome - let us know if you have any more problems.

**Comment by alpharulesirulee** [comment]
are you cracked? if you are buy minecraft 

are you premium? try restarting the launcher

**Comment by gdude2002** [comment]
@alpharulesirulee, please don't comment on resolved tickets.
