### ISSUE TITLE
Op Menu (Plugin)

### ISSUE THREAD

**Issue by DovahDoVolom** [GlowstoneMC/Glowstone-Legacy#590]
This plugin seems good to go other than the Sign not changing.
http://dev.bukkit.org/bukkit-plugins/opmenu/

**Comment by PaulBGD** [comment]
Good to know, however #28 says that the SignChangeEvent isn't implemented yet.

**Comment by turt2live** [comment]
Thanks for letting us know! Please refer to [the plugin compatibility article](https://github.com/GlowstoneMC/Glowstone/wiki/Plugin-Compatibility) for information on how to add this to the list.
