### ISSUE TITLE
PermissionsEx\PEX Not working (Plugin Error)

### ISSUE THREAD

**Issue by FlubberDunkies** [GlowstoneMC/Glowstone-Legacy#592]
Hi,
Currently on my server, I am encountering a error with PEX, and how it isn't loading on it. I can't figure out why its happening, but all I'm aware of is this error it gives me while starting:

"2014/12/19 13:12:01 [INFO] [Vault] Enabling Vault v1.5.0-b28
2014/12/19 13:12:01 [INFO] [Vault] [Economy] Essentials Economy found: Waiting
2014/12/19 13:12:01 [INFO] [Vault] [Permission] PermissionsEx found: Waiting
2014/12/19 13:12:01 [INFO] [Vault] [Permission] SuperPermissions loaded as backup permission system.
2014/12/19 13:12:02 [INFO] [Vault] [Chat] PermissionsEx found: Waiting
2014/12/19 13:12:02 [INFO] [Vault] Enabled Version 1.5.0-b28
2014/12/19 13:12:02 [INFO] Preparing spawn for world...
2014/12/19 13:12:03 [INFO] Preparing spawn for world: 23%
2014/12/19 13:12:04 [INFO] Preparing spawn for world: 53%
2014/12/19 13:12:05 [INFO] Preparing spawn for world: 87%
2014/12/19 13:12:05 [INFO] Preparing spawn for world: done
2014/12/19 13:12:05 [INFO] Preparing spawn for world_nether...
2014/12/19 13:12:06 [INFO] Preparing spawn for world_nether: 32%
2014/12/19 13:12:07 [INFO] Preparing spawn for world_nether: 65%
2014/12/19 13:12:08 [INFO] Preparing spawn for world_nether: done
2014/12/19 13:12:08 [INFO] Preparing spawn for world_the_end...
2014/12/19 13:12:09 [INFO] Preparing spawn for world_the_end: 34%
2014/12/19 13:12:10 [INFO] Preparing spawn for world_the_end: 68%
2014/12/19 13:12:11 [INFO] Preparing spawn for world_the_end: done
2014/12/19 13:12:11 [INFO] [PermissionsEx] Enabling PermissionsEx v1.23
2014/12/19 13:12:11 [INFO] [PermissionsEx] Disabling PermissionsEx v1.23
2014/12/19 13:12:11 [INFO] [Vault][Permission] PermissionsEx hooked.
2014/12/19 13:12:11 [INFO] [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
2014/12/19 13:12:12 [INFO] WEPIF: Using the Bukkit Permissions API.
2014/12/19 13:12:12 [WARNING] [WorldEdit] 

---

*\* This WorldEdit version does not fully support your version of Bukkit.
**
*\* When working with blocks or undoing, chests will be empty, signs
*\* will be blank, and so on. There will be no support for entity
*\* and biome-related functions.
**
*\* Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters

---

2014/12/19 13:12:12 [INFO] [Essentials] Enabling Essentials v2.13.1
2014/12/19 13:12:12 [INFO] Bukkit version format changed. Version not checked.
2014/12/19 13:12:12 [INFO] 1.8-134-g87fa006-b104
2014/12/19 13:12:12 [INFO] 1.8-R1-SNAPSHOT
2014/12/19 13:12:12 [SEVERE] [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/Ghv37Q. Full error:
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
    at ru.tehkode.permissions.RegExpMatcher.<init>(RegExpMatcher.java:17)
    at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:58)
    at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:164)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
    at net.glowstone.GlowServer.enablePlugins(GlowServer.java:632)
    at net.glowstone.GlowServer.start(GlowServer.java:431)
    at net.glowstone.GlowServer.main(GlowServer.java:100)

2014/12/19 13:12:12 [INFO] [Vault][Economy] Essentials Economy hooked.
2014/12/19 13:12:12 [INFO] Essentials: Using config file enhanced permissions.
2014/12/19 13:12:12 [INFO] Permissions listed in as player-commands will be given to all users.
2014/12/19 13:12:12 [INFO] [EssentialsProtect] Enabling EssentialsProtect v2.13.1
2014/12/19 13:12:12 [INFO] [EssentialsSpawn] Enabling EssentialsSpawn v2.13.1
2014/12/19 13:12:12 [INFO] [EssentialsAntiBuild] Enabling EssentialsAntiBuild v2.13.1
2014/12/19 13:12:12 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
2014/12/19 13:12:13 [INFO] Ready for connections."

Thats what comes up in the console. I don't know why this is happening. Can someone tell me why?
Thanks.

**Comment by gdude2002** [comment]
Hm, it appears that Bukkit ships some library as standard that Glowstone doesn't. There's an FAQ page [here](https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#a-plugin-that-uses-sql-or-some-other-library-doesnt-work), but I'm not entirely sure about a fix for this one right now.

If we don't manage to fix this, I'd appreciate if you submitted an entry on the [plugin compatibility form](http://goo.gl/forms/E8b3nmWAZw), as PEx is marked as working there.

**Comment by FlubberDunkies** [comment]
Alright, thanks for the help, ill submit a entry as-well so that the team can figure out the issue.

**Comment by PaulBGD** [comment]
We're using a new version of Guava. The Spigot team has made a version of PermissionsEx which supports this version, and it's available on their build server here:
https://hub.spigotmc.org/jenkins/view/All/job/PermissionsEx/

**Comment by dequis** [comment]
It's the other way around, actually. OP is using [PEX 1.23](http://dev.bukkit.org/bukkit-plugins/permissionsex/files/39-permissions-ex-v1-23/) which was updated to the newer guava, and we're using the same as craftbukkit 1.7

The linked release page says:

> This release is only compatible with 1.8 and above forks of Bukkit (and possibly SportBukkit). Tested using the Spigot 1.8 update

**Comment by FlubberDunkies** [comment]
Tried both of your methods, and also, thanks dequis! I tried downgrading the plugin version from 1.23 to 1.226. It now works beautifully. Thanks so much!

**Comment by PaulBGD** [comment]
@dequis Ah sorry, my mistake :) I figured it was one way or the other, and it looked like the other way around.

**Comment by gdude2002** [comment]
Glad it's sorted, please raise another ticket or a post on the forums if you have any more issues.
