### ISSUE TITLE
cant add ip to server. 

### ISSUE THREAD

**Issue by k3nny7ran** [GlowstoneMC/Glowstone-Legacy#595]
Help? On a mac

**Comment by turt2live** [comment]
What do you mean you can't add the IP? You shouldn't need to do any weird IP things.

**Comment by k3nny7ran** [comment]
It wont let friends join

**Comment by turt2live** [comment]
Due to the complexity involved in attempting to provide help, I think it may be best to join [IRC](http://webchat.esper.net/?nick=GS...&channels=glowstone&prompt=1).
