### ISSUE TITLE
cracked mc bug

### ISSUE THREAD

**Issue by parveshB** [GlowstoneMC/Glowstone-Legacy#596]
my friend uses a cracked minecraft so in order to let him join i make the online-mode= false
still cant then i make it to true but it cant too soo i think its a bug

**Comment by mamifsidtect** [comment]
You can always try removing or adding the -o argument to the end of your startup script after the jar file name. E.g: java -jar craftbukkit.jar -o

**Comment by mamifsidtect** [comment]
Of course, I don't condone pirating the game. If he likes the game that much, try to find him an official account :)

**Comment by turt2live** [comment]
We do not support cracked servers
