### ISSUE TITLE
Dropping and achievements problems

### ISSUE THREAD

**Issue by Whurauk** [GlowstoneMC/Glowstone-Legacy#598]
Hello. I found a bug in your new API. It turns out that I can't drop any block on the ground. If I break a block, it will end up directly in my inventory. I removed all my plugins in hopes of finding the one that is lacking but unfortunately none of my plugins is responsible of this bug. I also found another bug that makes appear the same achievements every time I enter the server. For example, I enter the server and I open my inventory . In the chat it said: Achievements Open Inventory. I disconnected from the server and I reconnected the same player without closing the server and still in the chat it said: Achievements Open Inventory. I hope to have an answer quickly. Thank you! :)

**Comment by greatman** [comment]
It is because dropping is still a WIP feature and I beleive there's a PR for it.

For the achivements i'm not sure. I'd have to see the code.

**Comment by gdude2002** [comment]
Item drops are definitely simply not done yet - as for achievements, I believe those are also WIP and I'd really be surprised if anyone's thought of looking at them yet, given their relative unimportance to the other stuff that needs doing right now.
