### ISSUE TITLE
Implement Spigot's Bukkit continuation?

### ISSUE THREAD

**Issue by ZephireNZ** [GlowstoneMC/Glowstone-Legacy#600]
Currently, we have Glowkit - our own fork of Bukkit circa 1.7. This meant that, when we updated to 1.8, we had to add in API for 1.8 features.

Spigot has now come out, with their own version of these features. Spigot's version of the API is undoubtably the more popular version being used.

Now that Spigot has been out for enough time for it to settle down, should we implement their version of the API? As it stands, we run the risk of being incompatible with many newer plugins that use most of the newer, incompatible, API calls. If we want to become a drop-in (or near to it) replacement for CraftBukkit, then we should consider doing this.

Perhaps we could change Glowkit to being a fork of the newer Bukkit, and then add any new features as needed. Or we could simply implement their Bukkit, and file any additions to the API to their repo (as they have stated they would prefer).

**Comment by gdude2002** [comment]
https://forums.glowstone.net/t/spigots-new-1-8-bukkit-api/68
