### ISSUE TITLE
High render-distance issues

### ISSUE THREAD

**Issue by PeaceDealer** [GlowstoneMC/Glowstone-Legacy#605]
Having a high render distance appears to create issues with the server...
I was monitoring the server and my pc very detailed when doing this, and there was no preformance issues on either.
These where my settings when the issue started to occur
http://prntscr.com/5qwhsj

![2015-01-11_00 20 49](https://cloud.githubusercontent.com/assets/996389/5693304/e3e2004c-9927-11e4-9cae-d1183a2c52c5.png)
![2015-01-11_00 20 54](https://cloud.githubusercontent.com/assets/996389/5693305/e3f52604-9927-11e4-9281-c9057af64c0e.png)

**Comment by ethsmith** [comment]
Sometimes it can be your computer or client as well we cant really be sure that it is glowstone, do you have an old computer or use optifine?

**Comment by gdude2002** [comment]
I would suggest testing this with the vanilla server and see if the same thing happens.

**Comment by PaulBGD** [comment]
Can confirm that artifacts like these show up with high render distances + moving fast

**Comment by gdude2002** [comment]
Paging @SpaceManiac

**Comment by turt2live** [comment]
This is an issue also on vanilla. It is due to the server having a lower render distance setting than the client and the client is trying to interpret world data that does not exist.

**Comment by turt2live** [comment]
I'm actually going to close this because it is a client-side issue. 

In short, and I think there is a Mojang ticket for it, the render distance on the client is larger than the render distance on the server. The server refuses to send more than it's configured maximum, but the client doesn't care and tries to render data out of range, which "gracefully" fails into the weird mess of chunks you see.

**Comment by jimmikaelkael** [comment]
@turt2live On a side note, it can be diminished by verifying the player can really see the chunk just before to fill the chunks map to send to the client in GlowPlayer.
That's what I am doing in #572. 

With this change it stops to happen altought you're moving fast.
