### ISSUE TITLE
Sponge API Implementation?

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone-Legacy#606]
Is it possibl for you to implement Sponge API and support Sponge plugins(not mods)? 
People are switching to Sponge API now.

**Comment by gdude2002** [comment]
We aren't at that stage yet.

There's some very not-serious testing stuff done by @SpaceManiac [here](https://github.com/GlowstoneMC/ShinySponge), but it just.. loads plugins and.. that's about it.

**Comment by gdude2002** [comment]
There's some discussion on this [on the forum](https://forums.glowstone.net/t/what-does-glowstone-plan-on-doing-after-implementing-bukkit/58/2) as well.

**Comment by SpaceManiac** [comment]
See #498, the linked repository, and the forum thread.

**Comment by DefinitlyEvil** [comment]
I got it, thanks.
