### ISSUE TITLE
Crafting Issue

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone-Legacy#610]
[rejected] WindowClickMessage(id=0, slot=0, button=
0, transaction=27, mode=0, item=ItemStack{WORKBENCH x 1})
It happens when player pick up the crafted item(output), recipes won't be removed and things may double.

**Comment by gdude2002** [comment]
Yes, this isn't done yet.

**Comment by DefinitlyEvil** [comment]
@gdude2002 I've checked the wiki and it says crafting is done. I guess that is a mistake? xD

**Comment by gdude2002** [comment]
#1 is _generally_ the go-to ticket for stuff like this.

**Comment by DefinitlyEvil** [comment]
@gdude2002 Okay, thanks. ;)
