### ISSUE TITLE
Wood blocks breaking problem

### ISSUE THREAD

**Issue by Pwsmooth** [GlowstoneMC/Glowstone-Legacy#611]
Whenever a wood block is placed on its side and broken it shows up a pink and black block as shown in the picture. But wood blocks that are placed upward and broken work just right.
![image](https://cloud.githubusercontent.com/assets/10405609/5770726/de83d7b2-9cf4-11e4-8ec5-473f96948e3f.png)

**Comment by dequis** [comment]
See #527

**Comment by turt2live** [comment]
I think this is a new issue, but it would be solved by #527. Closing as a duplicate
