### ISSUE TITLE
Destroying fire does not work

### ISSUE THREAD

**Issue by SpaceManiac** [GlowstoneMC/Glowstone-Legacy#612]
To remove fire, you start digging a block adjacent to it. Right now this instead destroys the dug block, and visually destroys the fire clientside without actually removing it.

DiggingHandler should be updated to detect the case where the dug block neighbors fire on the dug face and handle it by removing the fire and cancelling the dig.

Any fix should be tested in both survival and creative mode.

**Comment by m3rcuriel** [comment]
Should this still throw a `BlockDamageEvent` and/or `BlockBreakEvent`?

**Comment by SpaceManiac** [comment]
Tested on CB 1.7.10: no break event. Damage against the underlying block, but only in survival mode.

**Comment by m3rcuriel** [comment]
Alright, makes sense. Thanks.
