### ISSUE TITLE
Weather cannot be changed for non-default worlds

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#615]
Steps:
1) Create a new world (using MultiVerse or something)
2) Note the rain in that world
3) `/weather clear`
4) Nothing changes

**Comment by Tonodus** [comment]
This is caused due to the (false?) implementation of the bukkit wheather command I think. see [Bukkit/Bukkit WeatherCommand.java#L39](https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/command/defaults/WeatherCommand.java#L39)

**Comment by turt2live** [comment]
I have no idea. This is one of my many "unexpected behavior without research" tickets.

**Comment by SpaceManiac** [comment]
Fixed as of https://github.com/GlowstoneMC/Glowkit/commit/5290c315f7f2fd8a8c789831855f64305c1f2362.
