### ISSUE TITLE
Rejected using minecraft ingame-shortcuts

### ISSUE THREAD

**Issue by PeaceDealer** [GlowstoneMC/Glowstone-Legacy#617]
Hello

Just trying build 119 and went survival. Fetched some wood, put it in my crafting square, held shift and clicked.

It started to bug out really badly, duplicating the planks ect..

This is the error from the log:
[rejected] WindowClickMessage(id=0, slot=44, button=0, transaction=6, mode=0, item=ItemStack{WOOD x 16})

Glowstone Build: 119
OS: Debian
Java: 1.8.0_25

**Comment by gdude2002** [comment]
This isn't implemented properly yet, sorry. See #1.
