### ISSUE TITLE
DiggingMessage.FINISH_DIGGING not call

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#629]
Hello, `DiggingHandler.handle` don't call `DiggingMessage.FINISH_DIGGING` if the speed to break block is ~<0.05, based in [this table](http://minecraft.gamepedia.com/Breaking#Blocks_by_hardness)

CrabeMan.

**Comment by gdude2002** [comment]
What are the implications of this?

**Comment by ghost** [comment]
Edit: The implications are `BlockBreakEvent` cannot cancel this event and The durability is not calculate.

CrabeMan.

**Comment by turt2live** [comment]
What am I looking at in that table? All I see is numbers.

**Comment by bendem** [comment]
@turt2live looks like if you read the titles of the columns, you get a good idea of what these numbers are...

**Comment by turt2live** [comment]
but the numbers vary well between 0 and, in some cases, 6. What does 0.05 have anything to do with this?

**Comment by Cmdr3nder** [comment]
I believe I have witnessed what this causes on the client side:

Say you are breaking some `LONG_GRASS` and that only takes you 1 "hit" to break it. `DiggingHandler` only ever sees the `START_DIGGING` message and never the `FINISH_DIGGING` message for the `LONG_GRASS` block. This leads to things like item drops and other "block has been broken" actions from taking place.

This also appears to be reproducible with flowers and other instant dig blocks (probably any block that is in the 0.05 seconds to dig group on the table @CrabeMan linked.)

My Tentative Fix: https://github.com/ender4021/Glowstone/commit/7d629ba7c9882daee482077ebe9eaff5a872b100

**Comment by PaulBGD** [comment]
@ender4021 Feel free to make a PR, fix looks good.

**Comment by Tonodus** [comment]
This is a duplicate of #384

**Comment by Cmdr3nder** [comment]
@Tonodus Yes, it is. We should get #541 moving again.

@turt2live Perhaps this would be a good opportunity to close #642 and #629 in favor of #541 and #384? I think #541 is a more robust solution.

**Comment by turt2live** [comment]
Closing this as a duplicate of #384, #384 will be updated with some of the information presented here for reference. 

@ender4021 Both #642 and #541 will be reviewed independently and only then should they be compared.
