### ISSUE TITLE
Crafting is buggy

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone-Legacy#639]
Sometimes the output item will disappear on PC client. I don't think it is Dragonet's problem. 
Are you having this issue too? 
Thanks so much for helping. After fixing this bug, Glowstone can be used in production servers so does Dragonet.

**Comment by Johni0702** [comment]
This is known but hasn't been fully fixed by anyone yet. If you're interested in fixing it have a look there: #209

**Comment by ethsmith** [comment]
I don't think he's java programmer

**Comment by dequis** [comment]
@TekkitCommando He's the main developer of dragonet, another fork of glowstone. I sure hope he knows java.

**Comment by turt2live** [comment]
Closing as a duplicate of #1

**Comment by ethsmith** [comment]
Oh ok than I just didn't see any repositories haha

**Comment by DefinitlyEvil** [comment]
@turt2live I sorry this is duplicated. But how and why this happening? I mean the glitchy crafting.

**Comment by turt2live** [comment]
@DefinitlyEvil Because it's broken/not implemented.
