### ISSUE TITLE
Group Manager Not Working in Glowstone Servers

### ISSUE THREAD

**Issue by MCFinestPro** [GlowstoneMC/Glowstone-Legacy#641]
If someone could please help me with Group manager that would be awesome! When ever i try to use it on my server it wont let me do /help 
i also found this Error log i can show you if it helps
2015-05-26 19-36
=============================== GM ERROR LOG ===============================
= ERROR REPORT START - 2.1.31 (Phoenix) =

java.lang.NullPointerException
at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.setupWorldFolder(WorldsHolder.java:542)
at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.verifyFirstRun(WorldsHolder.java:536)
at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHolder(WorldsHolder.java:91)
at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.(WorldsHolder.java:59)
at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:179)
at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:103)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
at net.glowstone.GlowServer.enablePlugins(GlowServer.java:726)
at net.glowstone.GlowServer.start(GlowServer.java:477)
at net.glowstone.GlowServer.main(GlowServer.java:106)

here is my console to

19:36:18 [INFO] [Essentials] This will start 5 minutes after the first admin/op joins. 19:36:18 [INFO] Essentials: Using config file enhanced permissions. 19:36:18 [INFO] Permissions listed in as player-commands will be given to all us ers. 19:36:18 [INFO] [EssentialsProtect] Enabling EssentialsProtect v2.13.1 19:36:18 [INFO] [EssentialsSpawn] Enabling EssentialsSpawn v2.13.1 19:36:18 [INFO] [EssentialsChat] Enabling EssentialsChat v2.13.1 19:36:18 [INFO] [GroupManager] Enabling GroupManager v2.1.31 (Phoenix) 19:36:18 [WARNING] GroupManager - SEVERE - null 19:36:18 [WARNING] GroupManager - SEVERE - ===================================== ============== 19:36:18 [WARNING] GroupManager - SEVERE - = ERROR REPORT START - 2.1.31 (Phoeni x) = 19:36:18 [WARNING] GroupManager - SEVERE - ===================================== ============== 19:36:19 [WARNING] GroupManager - SEVERE - === PLEASE COPY AND PASTE THE ERROR.L OG FROM THE == 19:36:19 [WARNING] GroupManager - SEVERE - = GROUPMANAGER FOLDER TO AN ESSENTIAL S DEVELOPER = 19:36:19 [WARNING] GroupManager - SEVERE - ===================================== ============== 19:36:19 [WARNING] GroupManager - SEVERE - null 19:36:19 [WARNING] GroupManager - SEVERE - ===================================== ============== 19:36:19 [WARNING] GroupManager - SEVERE - = ERROR REPORT ENDED = 19:36:19 [WARNING] GroupManager - SEVERE - ===================================== ============== 19:36:19 [SEVERE] Error occurred while enabling GroupManager v2.1.31 (Phoenix) ( Is it up to date?) java.lang.IllegalArgumentException at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:24 8) at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:10 3) at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader .java:324) at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage r.java:404) at net.glowstone.GlowServer.enablePlugins(GlowServer.java:726) at net.glowstone.GlowServer.start(GlowServer.java:477) at net.glowstone.GlowServer.main(GlowServer.java:106) Caused by: java.lang.NullPointerException at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.setupWorldF older(WorldsHolder.java:542) at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.verifyFirst Run(WorldsHolder.java:536) at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorlds Holder(WorldsHolder.java:91) at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.(Worl dsHolder.java:59) at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:17 9) ... 7 more 19:36:19 [INFO] Essentials: Using GroupManager based permissions.

**Comment by turt2live** [comment]
GroupManager has a [known compatibility problem](https://docs.google.com/spreadsheets/d/1_dvf1v7OjmP0RcL2gTWOdnBYbYut5cHYKMUpRWlUrx8/edit#gid=0). Please refer to the [plugin compatibility list](https://docs.google.com/spreadsheets/d/1_dvf1v7OjmP0RcL2gTWOdnBYbYut5cHYKMUpRWlUrx8/edit#gid=0) for more information.

If you continue to have an issue, please let us know.

**Comment by turt2live** [comment]
@MCFinestPro Have you managed to resolve your issue?

**Comment by turt2live** [comment]
Closing this as inactive. @MCFinestPro if you continue to have issues please consult our [forums](http://forums.glowstone.net).
