### ISSUE TITLE
Add fire spreading feature

### ISSUE THREAD

**Issue by dtaillard** [GlowstoneMC/Glowstone-Legacy#645]
Currently, fire does not spread from one block to another (such as wood), instead it burns a single block infinitely.  Perhaps this feature could be implemented with different fire tick times for different types of blocks (e.g. wood will burn slower than planks).

**Comment by gdude2002** [comment]
Related to #509 (closed), #325 and perhaps #28 - Also possibly PR #249 

This feature simply isn't done yet - If you'd like to contribute a pull request, feel free, but until then, I'm going to close this ticket.
