### ISSUE TITLE
Block in armor slot

### ISSUE THREAD

**Issue by themineraria** [GlowstoneMC/Glowstone-Legacy#646]
I do the duplicat glitch and when i take my item, i can place then in any slot i want.
![2015-08-13_14 25 35](https://cloud.githubusercontent.com/assets/13781558/9249685/a37f7ffe-41c7-11e5-9184-7a513218fa81.png)

**Comment by gdude2002** [comment]
I don't understand; what duplicate glitch?

**Comment by themineraria** [comment]
this one : https://github.com/GlowstoneMC/Glowstone/issues/209

**Comment by gdude2002** [comment]
Well, if this is caused by the duplicate glitch then fixing that glitch (The fact that crafting is buggy, among other things that we already know about) will fix it.
